//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.04 at 10:26:25 AM ART 
//


package br.inf.portalfiscal.cte;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.inf.portalfiscal.cte package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory_inut {

    private final static QName _InutCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "inutCTe");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.inf.portalfiscal.cte
     * 
     */
    public ObjectFactory_inut() {
    }

    /**
     * Create an instance of {@link TRetInutCTe }
     * 
     */
    public TRetInutCTe createTRetInutCTe() {
        return new TRetInutCTe();
    }

    /**
     * Create an instance of {@link TInutCTe }
     * 
     */
    public TInutCTe createTInutCTe() {
        return new TInutCTe();
    }

    /**
     * Create an instance of {@link TProcInutCTe }
     * 
     */
    public TProcInutCTe createTProcInutCTe() {
        return new TProcInutCTe();
    }

    /**
     * Create an instance of {@link TRetInutCTe.InfInut }
     * 
     */
    public TRetInutCTe.InfInut createTRetInutCTeInfInut() {
        return new TRetInutCTe.InfInut();
    }

    /**
     * Create an instance of {@link TInutCTe.InfInut }
     * 
     */
    public TInutCTe.InfInut createTInutCTeInfInut() {
        return new TInutCTe.InfInut();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TInutCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "inutCTe")
    public JAXBElement<TInutCTe> createInutCTe(TInutCTe value) {
        return new JAXBElement<TInutCTe>(_InutCTe_QNAME, TInutCTe.class, null, value);
    }

}
