//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.04 at 10:28:27 AM ART 
//


package br.inf.portalfiscal.cte;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.inf.portalfiscal.cte package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory_consr {

    private final static QName _ConsReciCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "consReciCTe");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.inf.portalfiscal.cte
     * 
     */
    public ObjectFactory_consr() {
    }

    /**
     * Create an instance of {@link TProtCTe }
     * 
     */
    public TProtCTe createTProtCTe() {
        return new TProtCTe();
    }

    /**
     * Create an instance of {@link TConsReciCTe }
     * 
     */
    public TConsReciCTe createTConsReciCTe() {
        return new TConsReciCTe();
    }

    /**
     * Create an instance of {@link TRetConsReciCTe }
     * 
     */
    public TRetConsReciCTe createTRetConsReciCTe() {
        return new TRetConsReciCTe();
    }

    /**
     * Create an instance of {@link TProtCTe.InfProt }
     * 
     */
    public TProtCTe.InfProt createTProtCTeInfProt() {
        return new TProtCTe.InfProt();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TConsReciCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "consReciCTe")
    public static JAXBElement<TConsReciCTe> createConsReciCTe(TConsReciCTe value) {
        return new JAXBElement<TConsReciCTe>(_ConsReciCTe_QNAME, TConsReciCTe.class, null, value);
    }

}
