//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.29 at 01:58:16 PM ART 
//


package br.inf.portalfiscal.nfse;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CodObra" minOccurs="0"/>
 *         &lt;element ref="{}Art" minOccurs="0"/>
 *         &lt;element ref="{}ObraLog" minOccurs="0"/>
 *         &lt;element ref="{}ObraCompl" minOccurs="0"/>
 *         &lt;element ref="{}ObraNumero" minOccurs="0"/>
 *         &lt;element ref="{}ObraBairro" minOccurs="0"/>
 *         &lt;element ref="{}ObraCEP" minOccurs="0"/>
 *         &lt;element ref="{}ObraMun" minOccurs="0"/>
 *         &lt;element ref="{}ObraUF" minOccurs="0"/>
 *         &lt;element ref="{}ObraPais" minOccurs="0"/>
 *         &lt;element ref="{}ObraCEI" minOccurs="0"/>
 *         &lt;element ref="{}ObraMatricula" minOccurs="0"/>
 *         &lt;element ref="{}ObraValRedBC" minOccurs="0"/>
 *         &lt;element ref="{}ObraTipo" minOccurs="0"/>
 *         &lt;element ref="{}ObraNumEncapsulamento" minOccurs="0"/>
 *         &lt;element ref="{}AbatimentoMateriais" minOccurs="0"/>
 *         &lt;element ref="{}ListaMaterial" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codObra",
    "art",
    "obraLog",
    "obraCompl",
    "obraNumero",
    "obraBairro",
    "obraCEP",
    "obraMun",
    "obraUF",
    "obraPais",
    "obraCEI",
    "obraMatricula",
    "obraValRedBC",
    "obraTipo",
    "obraNumEncapsulamento",
    "abatimentoMateriais",
    "listaMaterial"
})
@XmlRootElement(name = "ConstCivil")
public class ConstCivil {

    @XmlElement(name = "CodObra")
    protected String codObra;
    @XmlElement(name = "Art")
    protected String art;
    @XmlElement(name = "ObraLog")
    protected String obraLog;
    @XmlElement(name = "ObraCompl")
    protected String obraCompl;
    @XmlElement(name = "ObraNumero")
    protected String obraNumero;
    @XmlElement(name = "ObraBairro")
    protected String obraBairro;
    @XmlElement(name = "ObraCEP")
    protected BigInteger obraCEP;
    @XmlElement(name = "ObraMun")
    protected BigInteger obraMun;
    @XmlElement(name = "ObraUF")
    protected String obraUF;
    @XmlElement(name = "ObraPais")
    protected String obraPais;
    @XmlElement(name = "ObraCEI")
    protected String obraCEI;
    @XmlElement(name = "ObraMatricula")
    protected String obraMatricula;
    @XmlElement(name = "ObraValRedBC")
    protected BigDecimal obraValRedBC;
    @XmlElement(name = "ObraTipo")
    protected BigInteger obraTipo;
    @XmlElement(name = "ObraNumEncapsulamento")
    protected BigInteger obraNumEncapsulamento;
    @XmlElement(name = "AbatimentoMateriais")
    protected BigInteger abatimentoMateriais;
    @XmlElement(name = "ListaMaterial")
    protected List<ListaMaterial> listaMaterial;

    /**
     * Gets the value of the codObra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodObra() {
        return codObra;
    }

    /**
     * Sets the value of the codObra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodObra(String value) {
        this.codObra = value;
    }

    /**
     * Gets the value of the art property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArt() {
        return art;
    }

    /**
     * Sets the value of the art property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArt(String value) {
        this.art = value;
    }

    /**
     * Gets the value of the obraLog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObraLog() {
        return obraLog;
    }

    /**
     * Sets the value of the obraLog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObraLog(String value) {
        this.obraLog = value;
    }

    /**
     * Gets the value of the obraCompl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObraCompl() {
        return obraCompl;
    }

    /**
     * Sets the value of the obraCompl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObraCompl(String value) {
        this.obraCompl = value;
    }

    /**
     * Gets the value of the obraNumero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObraNumero() {
        return obraNumero;
    }

    /**
     * Sets the value of the obraNumero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObraNumero(String value) {
        this.obraNumero = value;
    }

    /**
     * Gets the value of the obraBairro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObraBairro() {
        return obraBairro;
    }

    /**
     * Sets the value of the obraBairro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObraBairro(String value) {
        this.obraBairro = value;
    }

    /**
     * Gets the value of the obraCEP property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getObraCEP() {
        return obraCEP;
    }

    /**
     * Sets the value of the obraCEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setObraCEP(BigInteger value) {
        this.obraCEP = value;
    }

    /**
     * Gets the value of the obraMun property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getObraMun() {
        return obraMun;
    }

    /**
     * Sets the value of the obraMun property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setObraMun(BigInteger value) {
        this.obraMun = value;
    }

    /**
     * Gets the value of the obraUF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObraUF() {
        return obraUF;
    }

    /**
     * Sets the value of the obraUF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObraUF(String value) {
        this.obraUF = value;
    }

    /**
     * Gets the value of the obraPais property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObraPais() {
        return obraPais;
    }

    /**
     * Sets the value of the obraPais property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObraPais(String value) {
        this.obraPais = value;
    }

    /**
     * Gets the value of the obraCEI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObraCEI() {
        return obraCEI;
    }

    /**
     * Sets the value of the obraCEI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObraCEI(String value) {
        this.obraCEI = value;
    }

    /**
     * Gets the value of the obraMatricula property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObraMatricula() {
        return obraMatricula;
    }

    /**
     * Sets the value of the obraMatricula property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObraMatricula(String value) {
        this.obraMatricula = value;
    }

    /**
     * Gets the value of the obraValRedBC property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getObraValRedBC() {
        return obraValRedBC;
    }

    /**
     * Sets the value of the obraValRedBC property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setObraValRedBC(BigDecimal value) {
        this.obraValRedBC = value;
    }

    /**
     * Gets the value of the obraTipo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getObraTipo() {
        return obraTipo;
    }

    /**
     * Sets the value of the obraTipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setObraTipo(BigInteger value) {
        this.obraTipo = value;
    }

    /**
     * Gets the value of the obraNumEncapsulamento property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getObraNumEncapsulamento() {
        return obraNumEncapsulamento;
    }

    /**
     * Sets the value of the obraNumEncapsulamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setObraNumEncapsulamento(BigInteger value) {
        this.obraNumEncapsulamento = value;
    }

    /**
     * Gets the value of the abatimentoMateriais property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAbatimentoMateriais() {
        return abatimentoMateriais;
    }

    /**
     * Sets the value of the abatimentoMateriais property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAbatimentoMateriais(BigInteger value) {
        this.abatimentoMateriais = value;
    }

    /**
     * Gets the value of the listaMaterial property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listaMaterial property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListaMaterial().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ListaMaterial }
     * 
     * 
     */
    public List<ListaMaterial> getListaMaterial() {
        if (listaMaterial == null) {
            listaMaterial = new ArrayList<ListaMaterial>();
        }
        return this.listaMaterial;
    }

}
