//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.06 at 09:40:46 AM ART 
//


package br.inf.portalfiscal.nfse;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CNPJ"/>
 *         &lt;element ref="{}NFSeNumero"/>
 *         &lt;element ref="{}RPSNumero"/>
 *         &lt;element ref="{}RPSSerie"/>
 *         &lt;element ref="{}EveTp"/>
 *         &lt;element ref="{}tpAmb"/>
 *         &lt;element ref="{}EveCodigo"/>
 *         &lt;element ref="{}EveMotivo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cnpj",
    "nfSeNumero",
    "rpsNumero",
    "rpsSerie",
    "eveTp",
    "tpAmb",
    "eveCodigo",
    "eveMotivo"
})
@XmlRootElement(name = "Evento")
public class Evento {

    @XmlElement(name = "CNPJ", required = true)
    protected String cnpj;
    @XmlElement(name = "NFSeNumero", required = true)
    protected BigInteger nfSeNumero;
    @XmlElement(name = "RPSNumero", required = true)
    protected BigInteger rpsNumero;
    @XmlElement(name = "RPSSerie", required = true)
    protected String rpsSerie;
    @XmlElement(name = "EveTp", required = true)
    protected BigInteger eveTp;
    @XmlElement(required = true)
    protected BigInteger tpAmb;
    @XmlElement(name = "EveCodigo", required = true)
    protected String eveCodigo;
    @XmlElement(name = "EveMotivo", required = true)
    protected String eveMotivo;

    /**
     * Gets the value of the cnpj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNPJ() {
        return cnpj;
    }

    /**
     * Sets the value of the cnpj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNPJ(String value) {
        this.cnpj = value;
    }

    /**
     * Gets the value of the nfSeNumero property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNFSeNumero() {
        return nfSeNumero;
    }

    /**
     * Sets the value of the nfSeNumero property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNFSeNumero(BigInteger value) {
        this.nfSeNumero = value;
    }

    /**
     * Gets the value of the rpsNumero property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRPSNumero() {
        return rpsNumero;
    }

    /**
     * Sets the value of the rpsNumero property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRPSNumero(BigInteger value) {
        this.rpsNumero = value;
    }

    /**
     * Gets the value of the rpsSerie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRPSSerie() {
        return rpsSerie;
    }

    /**
     * Sets the value of the rpsSerie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRPSSerie(String value) {
        this.rpsSerie = value;
    }

    /**
     * Gets the value of the eveTp property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEveTp() {
        return eveTp;
    }

    /**
     * Sets the value of the eveTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEveTp(BigInteger value) {
        this.eveTp = value;
    }

    /**
     * Gets the value of the tpAmb property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTpAmb() {
        return tpAmb;
    }

    /**
     * Sets the value of the tpAmb property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTpAmb(BigInteger value) {
        this.tpAmb = value;
    }

    /**
     * Gets the value of the eveCodigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEveCodigo() {
        return eveCodigo;
    }

    /**
     * Sets the value of the eveCodigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEveCodigo(String value) {
        this.eveCodigo = value;
    }

    /**
     * Gets the value of the eveMotivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEveMotivo() {
        return eveMotivo;
    }

    /**
     * Sets the value of the eveMotivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEveMotivo(String value) {
        this.eveMotivo = value;
    }

}
