//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.29 at 01:58:16 PM ART 
//


package br.inf.portalfiscal.nfse;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}IntermRazaoSocial"/>
 *         &lt;element ref="{}IntermCNPJ"/>
 *         &lt;element ref="{}IntermCPF"/>
 *         &lt;element ref="{}IntermIM" minOccurs="0"/>
 *         &lt;element ref="{}IntermEmail" minOccurs="0"/>
 *         &lt;element ref="{}IntermEndereco"/>
 *         &lt;element ref="{}IntermNumero"/>
 *         &lt;element ref="{}IntermComplemento"/>
 *         &lt;element ref="{}IntermBairro"/>
 *         &lt;element ref="{}IntermCep"/>
 *         &lt;element ref="{}IntermCmun"/>
 *         &lt;element ref="{}IntermXmun"/>
 *         &lt;element ref="{}IntermFone"/>
 *         &lt;element ref="{}ItermIE"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "intermRazaoSocial",
    "intermCNPJ",
    "intermCPF",
    "intermIM",
    "intermEmail",
    "intermEndereco",
    "intermNumero",
    "intermComplemento",
    "intermBairro",
    "intermCep",
    "intermCmun",
    "intermXmun",
    "intermFone",
    "itermIE"
})
@XmlRootElement(name = "IntermServico")
public class IntermServico {

    @XmlElement(name = "IntermRazaoSocial", required = true)
    protected String intermRazaoSocial;
    @XmlElement(name = "IntermCNPJ", required = true)
    protected String intermCNPJ;
    @XmlElement(name = "IntermCPF", required = true)
    protected String intermCPF;
    @XmlElement(name = "IntermIM")
    protected String intermIM;
    @XmlElement(name = "IntermEmail")
    protected String intermEmail;
    @XmlElement(name = "IntermEndereco", required = true)
    protected String intermEndereco;
    @XmlElement(name = "IntermNumero", required = true)
    protected String intermNumero;
    @XmlElement(name = "IntermComplemento", required = true)
    protected String intermComplemento;
    @XmlElement(name = "IntermBairro", required = true)
    protected String intermBairro;
    @XmlElement(name = "IntermCep", required = true)
    protected String intermCep;
    @XmlElement(name = "IntermCmun", required = true)
    protected BigInteger intermCmun;
    @XmlElement(name = "IntermXmun", required = true)
    protected String intermXmun;
    @XmlElement(name = "IntermFone", required = true)
    protected String intermFone;
    @XmlElement(name = "ItermIE", required = true)
    protected String itermIE;

    /**
     * Gets the value of the intermRazaoSocial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntermRazaoSocial() {
        return intermRazaoSocial;
    }

    /**
     * Sets the value of the intermRazaoSocial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermRazaoSocial(String value) {
        this.intermRazaoSocial = value;
    }

    /**
     * Gets the value of the intermCNPJ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntermCNPJ() {
        return intermCNPJ;
    }

    /**
     * Sets the value of the intermCNPJ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermCNPJ(String value) {
        this.intermCNPJ = value;
    }

    /**
     * Gets the value of the intermCPF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntermCPF() {
        return intermCPF;
    }

    /**
     * Sets the value of the intermCPF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermCPF(String value) {
        this.intermCPF = value;
    }

    /**
     * Gets the value of the intermIM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntermIM() {
        return intermIM;
    }

    /**
     * Sets the value of the intermIM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermIM(String value) {
        this.intermIM = value;
    }

    /**
     * Gets the value of the intermEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntermEmail() {
        return intermEmail;
    }

    /**
     * Sets the value of the intermEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermEmail(String value) {
        this.intermEmail = value;
    }

    /**
     * Gets the value of the intermEndereco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntermEndereco() {
        return intermEndereco;
    }

    /**
     * Sets the value of the intermEndereco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermEndereco(String value) {
        this.intermEndereco = value;
    }

    /**
     * Gets the value of the intermNumero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntermNumero() {
        return intermNumero;
    }

    /**
     * Sets the value of the intermNumero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermNumero(String value) {
        this.intermNumero = value;
    }

    /**
     * Gets the value of the intermComplemento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntermComplemento() {
        return intermComplemento;
    }

    /**
     * Sets the value of the intermComplemento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermComplemento(String value) {
        this.intermComplemento = value;
    }

    /**
     * Gets the value of the intermBairro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntermBairro() {
        return intermBairro;
    }

    /**
     * Sets the value of the intermBairro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermBairro(String value) {
        this.intermBairro = value;
    }

    /**
     * Gets the value of the intermCep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntermCep() {
        return intermCep;
    }

    /**
     * Sets the value of the intermCep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermCep(String value) {
        this.intermCep = value;
    }

    /**
     * Gets the value of the intermCmun property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIntermCmun() {
        return intermCmun;
    }

    /**
     * Sets the value of the intermCmun property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIntermCmun(BigInteger value) {
        this.intermCmun = value;
    }

    /**
     * Gets the value of the intermXmun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntermXmun() {
        return intermXmun;
    }

    /**
     * Sets the value of the intermXmun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermXmun(String value) {
        this.intermXmun = value;
    }

    /**
     * Gets the value of the intermFone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntermFone() {
        return intermFone;
    }

    /**
     * Sets the value of the intermFone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermFone(String value) {
        this.intermFone = value;
    }

    /**
     * Gets the value of the itermIE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItermIE() {
        return itermIE;
    }

    /**
     * Sets the value of the itermIE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItermIE(String value) {
        this.itermIE = value;
    }

}
