//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.29 at 01:58:16 PM ART 
//


package br.inf.portalfiscal.nfse;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ded" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DedSeq">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *                         &lt;totalDigits value="18"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="DedValPer">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="3"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="DedTipo">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="3"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="DedCNPJRef" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="14"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="DedCPFRef" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="11"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="DednNFRef" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *                         &lt;totalDigits value="10"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="DedvlTotRef" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;totalDigits value="16"/>
 *                         &lt;fractionDigits value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="DedPer" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;totalDigits value="16"/>
 *                         &lt;fractionDigits value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="DedValor">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;totalDigits value="16"/>
 *                         &lt;fractionDigits value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element ref="{}DedQtde" minOccurs="0"/>
 *                   &lt;element ref="{}DedValUnit" minOccurs="0"/>
 *                   &lt;element ref="{}DedDescricao" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ded"
})
@XmlRootElement(name = "ListaDed")
public class ListaDed {

    @XmlElement(name = "Ded", required = true)
    protected List<ListaDed.Ded> ded;

    /**
     * Gets the value of the ded property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ded property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ListaDed.Ded }
     * 
     * 
     */
    public List<ListaDed.Ded> getDed() {
        if (ded == null) {
            ded = new ArrayList<ListaDed.Ded>();
        }
        return this.ded;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DedSeq">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
     *               &lt;totalDigits value="18"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="DedValPer">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="3"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="DedTipo">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="3"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="DedCNPJRef" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="14"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="DedCPFRef" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="11"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="DednNFRef" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
     *               &lt;totalDigits value="10"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="DedvlTotRef" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;totalDigits value="16"/>
     *               &lt;fractionDigits value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="DedPer" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;totalDigits value="16"/>
     *               &lt;fractionDigits value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="DedValor">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;totalDigits value="16"/>
     *               &lt;fractionDigits value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element ref="{}DedQtde" minOccurs="0"/>
     *         &lt;element ref="{}DedValUnit" minOccurs="0"/>
     *         &lt;element ref="{}DedDescricao" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dedSeq",
        "dedValPer",
        "dedTipo",
        "dedCNPJRef",
        "dedCPFRef",
        "dednNFRef",
        "dedvlTotRef",
        "dedPer",
        "dedValor",
        "dedQtde",
        "dedValUnit",
        "dedDescricao"
    })
    public static class Ded {

        @XmlElement(name = "DedSeq", required = true)
        protected BigInteger dedSeq;
        @XmlElement(name = "DedValPer", required = true)
        protected String dedValPer;
        @XmlElement(name = "DedTipo", required = true)
        protected String dedTipo;
        @XmlElement(name = "DedCNPJRef")
        protected String dedCNPJRef;
        @XmlElement(name = "DedCPFRef")
        protected String dedCPFRef;
        @XmlElement(name = "DednNFRef")
        protected BigInteger dednNFRef;
        @XmlElement(name = "DedvlTotRef")
        protected BigDecimal dedvlTotRef;
        @XmlElement(name = "DedPer")
        protected BigDecimal dedPer;
        @XmlElement(name = "DedValor", required = true)
        protected BigDecimal dedValor;
        @XmlElement(name = "DedQtde")
        protected BigDecimal dedQtde;
        @XmlElement(name = "DedValUnit")
        protected BigDecimal dedValUnit;
        @XmlElement(name = "DedDescricao")
        protected String dedDescricao;

        /**
         * Gets the value of the dedSeq property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getDedSeq() {
            return dedSeq;
        }

        /**
         * Sets the value of the dedSeq property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setDedSeq(BigInteger value) {
            this.dedSeq = value;
        }

        /**
         * Gets the value of the dedValPer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDedValPer() {
            return dedValPer;
        }

        /**
         * Sets the value of the dedValPer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDedValPer(String value) {
            this.dedValPer = value;
        }

        /**
         * Gets the value of the dedTipo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDedTipo() {
            return dedTipo;
        }

        /**
         * Sets the value of the dedTipo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDedTipo(String value) {
            this.dedTipo = value;
        }

        /**
         * Gets the value of the dedCNPJRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDedCNPJRef() {
            return dedCNPJRef;
        }

        /**
         * Sets the value of the dedCNPJRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDedCNPJRef(String value) {
            this.dedCNPJRef = value;
        }

        /**
         * Gets the value of the dedCPFRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDedCPFRef() {
            return dedCPFRef;
        }

        /**
         * Sets the value of the dedCPFRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDedCPFRef(String value) {
            this.dedCPFRef = value;
        }

        /**
         * Gets the value of the dednNFRef property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getDednNFRef() {
            return dednNFRef;
        }

        /**
         * Sets the value of the dednNFRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setDednNFRef(BigInteger value) {
            this.dednNFRef = value;
        }

        /**
         * Gets the value of the dedvlTotRef property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDedvlTotRef() {
            return dedvlTotRef;
        }

        /**
         * Sets the value of the dedvlTotRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDedvlTotRef(BigDecimal value) {
            this.dedvlTotRef = value;
        }

        /**
         * Gets the value of the dedPer property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDedPer() {
            return dedPer;
        }

        /**
         * Sets the value of the dedPer property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDedPer(BigDecimal value) {
            this.dedPer = value;
        }

        /**
         * Gets the value of the dedValor property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDedValor() {
            return dedValor;
        }

        /**
         * Sets the value of the dedValor property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDedValor(BigDecimal value) {
            this.dedValor = value;
        }

        /**
         * Gets the value of the dedQtde property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDedQtde() {
            return dedQtde;
        }

        /**
         * Sets the value of the dedQtde property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDedQtde(BigDecimal value) {
            this.dedQtde = value;
        }

        /**
         * Gets the value of the dedValUnit property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDedValUnit() {
            return dedValUnit;
        }

        /**
         * Sets the value of the dedValUnit property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDedValUnit(BigDecimal value) {
            this.dedValUnit = value;
        }

        /**
         * Gets the value of the dedDescricao property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDedDescricao() {
            return dedDescricao;
        }

        /**
         * Sets the value of the dedDescricao property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDedDescricao(String value) {
            this.dedDescricao = value;
        }

    }

}
