//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.29 at 01:58:16 PM ART 
//


package br.inf.portalfiscal.nfse;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Item" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}ItemSeq"/>
 *                   &lt;element ref="{}ItemCod"/>
 *                   &lt;element ref="{}ItemDesc"/>
 *                   &lt;element ref="{}ItemQtde"/>
 *                   &lt;element ref="{}ItemvUnit"/>
 *                   &lt;element ref="{}ItemuMed" minOccurs="0"/>
 *                   &lt;element ref="{}ItemvlDed" minOccurs="0"/>
 *                   &lt;element ref="{}ItemTributavel" minOccurs="0"/>
 *                   &lt;element ref="{}ItemcCnae" minOccurs="0"/>
 *                   &lt;element ref="{}ItemTributMunicipio" minOccurs="0"/>
 *                   &lt;element ref="{}ItemnAlvara" minOccurs="0"/>
 *                   &lt;element ref="{}ItemvIss"/>
 *                   &lt;element ref="{}ItemvDesconto" minOccurs="0"/>
 *                   &lt;element ref="{}ItemAliquota"/>
 *                   &lt;element ref="{}ItemVlrTotal" minOccurs="0"/>
 *                   &lt;element ref="{}ItemBaseCalculo"/>
 *                   &lt;element ref="{}ItemvlrISSRetido" minOccurs="0"/>
 *                   &lt;element ref="{}ItemIssRetido"/>
 *                   &lt;element ref="{}ItemRespRetencao" minOccurs="0"/>
 *                   &lt;element ref="{}ItemIteListServico"/>
 *                   &lt;element ref="{}ItemExigibilidadeISS"/>
 *                   &lt;element ref="{}ItemcMunIncidencia" minOccurs="0"/>
 *                   &lt;element ref="{}ItemNumProcesso" minOccurs="0"/>
 *                   &lt;element ref="{}ItemDedTipo" minOccurs="0"/>
 *                   &lt;element ref="{}ItemDedCPFRef" minOccurs="0"/>
 *                   &lt;element ref="{}ItemDedCNPJRef" minOccurs="0"/>
 *                   &lt;element ref="{}ItemDedNFRef" minOccurs="0"/>
 *                   &lt;element ref="{}ItemDedvlTotRef" minOccurs="0"/>
 *                   &lt;element ref="{}ItemDedPer" minOccurs="0"/>
 *                   &lt;element ref="{}ItemVlrLiquido" minOccurs="0"/>
 *                   &lt;element ref="{}ItemValAliqINSS" minOccurs="0"/>
 *                   &lt;element ref="{}ItemValINSS" minOccurs="0"/>
 *                   &lt;element ref="{}ItemValAliqIR" minOccurs="0"/>
 *                   &lt;element ref="{}ItemValIR" minOccurs="0"/>
 *                   &lt;element ref="{}ItemValAliqCOFINS" minOccurs="0"/>
 *                   &lt;element ref="{}ItemValCOFINS" minOccurs="0"/>
 *                   &lt;element ref="{}ItemValAliqCSLL" minOccurs="0"/>
 *                   &lt;element ref="{}ItemValCSLL" minOccurs="0"/>
 *                   &lt;element ref="{}ItemValAliqPIS " minOccurs="0"/>
 *                   &lt;element ref="{}ItemValPIS" minOccurs="0"/>
 *                   &lt;element ref="{}ItemRedBCRetido" minOccurs="0"/>
 *                   &lt;element ref="{}ItemBCRetido" minOccurs="0"/>
 *                   &lt;element ref="{}ItemPaisImpDevido" minOccurs="0"/>
 *                   &lt;element ref="{}ItemValAliqISSRetido" minOccurs="0"/>
 *                   &lt;element ref="{}ItemJustDed" minOccurs="0"/>
 *                   &lt;element ref="{}ItemvOutrasRetencoes" minOccurs="0"/>
 *                   &lt;element ref="{}ItemDescIncondicionado" minOccurs="0"/>
 *                   &lt;element ref="{}ItemDescCondicionado" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "item"
})
@XmlRootElement(name = "ListaItens")
public class ListaItens {

    @XmlElement(name = "Item", required = true)
    protected List<ListaItens.Item> item;

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ListaItens.Item }
     * 
     * 
     */
    public List<ListaItens.Item> getItem() {
        if (item == null) {
            item = new ArrayList<ListaItens.Item>();
        }
        return this.item;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}ItemSeq"/>
     *         &lt;element ref="{}ItemCod"/>
     *         &lt;element ref="{}ItemDesc"/>
     *         &lt;element ref="{}ItemQtde"/>
     *         &lt;element ref="{}ItemvUnit"/>
     *         &lt;element ref="{}ItemuMed" minOccurs="0"/>
     *         &lt;element ref="{}ItemvlDed" minOccurs="0"/>
     *         &lt;element ref="{}ItemTributavel" minOccurs="0"/>
     *         &lt;element ref="{}ItemcCnae" minOccurs="0"/>
     *         &lt;element ref="{}ItemTributMunicipio" minOccurs="0"/>
     *         &lt;element ref="{}ItemnAlvara" minOccurs="0"/>
     *         &lt;element ref="{}ItemvIss"/>
     *         &lt;element ref="{}ItemvDesconto" minOccurs="0"/>
     *         &lt;element ref="{}ItemAliquota"/>
     *         &lt;element ref="{}ItemVlrTotal" minOccurs="0"/>
     *         &lt;element ref="{}ItemBaseCalculo"/>
     *         &lt;element ref="{}ItemvlrISSRetido" minOccurs="0"/>
     *         &lt;element ref="{}ItemIssRetido"/>
     *         &lt;element ref="{}ItemRespRetencao" minOccurs="0"/>
     *         &lt;element ref="{}ItemIteListServico"/>
     *         &lt;element ref="{}ItemExigibilidadeISS"/>
     *         &lt;element ref="{}ItemcMunIncidencia" minOccurs="0"/>
     *         &lt;element ref="{}ItemNumProcesso" minOccurs="0"/>
     *         &lt;element ref="{}ItemDedTipo" minOccurs="0"/>
     *         &lt;element ref="{}ItemDedCPFRef" minOccurs="0"/>
     *         &lt;element ref="{}ItemDedCNPJRef" minOccurs="0"/>
     *         &lt;element ref="{}ItemDedNFRef" minOccurs="0"/>
     *         &lt;element ref="{}ItemDedvlTotRef" minOccurs="0"/>
     *         &lt;element ref="{}ItemDedPer" minOccurs="0"/>
     *         &lt;element ref="{}ItemVlrLiquido" minOccurs="0"/>
     *         &lt;element ref="{}ItemValAliqINSS" minOccurs="0"/>
     *         &lt;element ref="{}ItemValINSS" minOccurs="0"/>
     *         &lt;element ref="{}ItemValAliqIR" minOccurs="0"/>
     *         &lt;element ref="{}ItemValIR" minOccurs="0"/>
     *         &lt;element ref="{}ItemValAliqCOFINS" minOccurs="0"/>
     *         &lt;element ref="{}ItemValCOFINS" minOccurs="0"/>
     *         &lt;element ref="{}ItemValAliqCSLL" minOccurs="0"/>
     *         &lt;element ref="{}ItemValCSLL" minOccurs="0"/>
     *         &lt;element ref="{}ItemValAliqPIS " minOccurs="0"/>
     *         &lt;element ref="{}ItemValPIS" minOccurs="0"/>
     *         &lt;element ref="{}ItemRedBCRetido" minOccurs="0"/>
     *         &lt;element ref="{}ItemBCRetido" minOccurs="0"/>
     *         &lt;element ref="{}ItemPaisImpDevido" minOccurs="0"/>
     *         &lt;element ref="{}ItemValAliqISSRetido" minOccurs="0"/>
     *         &lt;element ref="{}ItemJustDed" minOccurs="0"/>
     *         &lt;element ref="{}ItemvOutrasRetencoes" minOccurs="0"/>
     *         &lt;element ref="{}ItemDescIncondicionado" minOccurs="0"/>
     *         &lt;element ref="{}ItemDescCondicionado" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "itemSeq",
        "itemCod",
        "itemDesc",
        "itemQtde",
        "itemvUnit",
        "itemuMed",
        "itemvlDed",
        "itemTributavel",
        "itemcCnae",
        "itemTributMunicipio",
        "itemnAlvara",
        "itemvIss",
        "itemvDesconto",
        "itemAliquota",
        "itemVlrTotal",
        "itemBaseCalculo",
        "itemvlrISSRetido",
        "itemIssRetido",
        "itemRespRetencao",
        "itemIteListServico",
        "itemExigibilidadeISS",
        "itemcMunIncidencia",
        "itemNumProcesso",
        "itemDedTipo",
        "itemDedCPFRef",
        "itemDedCNPJRef",
        "itemDedNFRef",
        "itemDedvlTotRef",
        "itemDedPer",
        "itemVlrLiquido",
        "itemValAliqINSS",
        "itemValINSS",
        "itemValAliqIR",
        "itemValIR",
        "itemValAliqCOFINS",
        "itemValCOFINS",
        "itemValAliqCSLL",
        "itemValCSLL",
        "itemValAliqPIS0020",
        "itemValPIS",
        "itemRedBCRetido",
        "itemBCRetido",
        "itemPaisImpDevido",
        "itemValAliqISSRetido",
        "itemJustDed",
        "itemvOutrasRetencoes",
        "itemDescIncondicionado",
        "itemDescCondicionado"
    })
    public static class Item {

        @XmlElement(name = "ItemSeq", required = true)
        protected BigInteger itemSeq;
        @XmlElement(name = "ItemCod", required = true)
        protected String itemCod;
        @XmlElement(name = "ItemDesc", required = true)
        protected String itemDesc;
        @XmlElement(name = "ItemQtde", required = true)
        protected BigDecimal itemQtde;
        @XmlElement(name = "ItemvUnit", required = true)
        protected BigDecimal itemvUnit;
        @XmlElement(name = "ItemuMed")
        protected String itemuMed;
        @XmlElement(name = "ItemvlDed")
        protected BigDecimal itemvlDed;
        @XmlElement(name = "ItemTributavel")
        protected String itemTributavel;
        @XmlElement(name = "ItemcCnae")
        protected BigInteger itemcCnae;
        @XmlElement(name = "ItemTributMunicipio")
        protected String itemTributMunicipio;
        @XmlElement(name = "ItemnAlvara")
        protected String itemnAlvara;
        @XmlElement(name = "ItemvIss", required = true)
        protected BigDecimal itemvIss;
        @XmlElement(name = "ItemvDesconto")
        protected BigDecimal itemvDesconto;
        @XmlElement(name = "ItemAliquota", required = true)
        protected BigDecimal itemAliquota;
        @XmlElement(name = "ItemVlrTotal")
        protected BigDecimal itemVlrTotal;
        @XmlElement(name = "ItemBaseCalculo", required = true)
        protected BigDecimal itemBaseCalculo;
        @XmlElement(name = "ItemvlrISSRetido")
        protected BigDecimal itemvlrISSRetido;
        @XmlElement(name = "ItemIssRetido")
        protected int itemIssRetido;
        @XmlElement(name = "ItemRespRetencao")
        protected Integer itemRespRetencao;
        @XmlElement(name = "ItemIteListServico", required = true)
        protected String itemIteListServico;
        @XmlElement(name = "ItemExigibilidadeISS", required = true)
        protected BigInteger itemExigibilidadeISS;
        @XmlElement(name = "ItemcMunIncidencia")
        protected BigInteger itemcMunIncidencia;
        @XmlElement(name = "ItemNumProcesso")
        protected String itemNumProcesso;
        @XmlElement(name = "ItemDedTipo")
        protected String itemDedTipo;
        @XmlElement(name = "ItemDedCPFRef")
        protected String itemDedCPFRef;
        @XmlElement(name = "ItemDedCNPJRef")
        protected String itemDedCNPJRef;
        @XmlElement(name = "ItemDedNFRef")
        protected BigInteger itemDedNFRef;
        @XmlElement(name = "ItemDedvlTotRef")
        protected BigDecimal itemDedvlTotRef;
        @XmlElement(name = "ItemDedPer")
        protected BigDecimal itemDedPer;
        @XmlElement(name = "ItemVlrLiquido")
        protected BigDecimal itemVlrLiquido;
        @XmlElement(name = "ItemValAliqINSS")
        protected BigDecimal itemValAliqINSS;
        @XmlElement(name = "ItemValINSS")
        protected BigDecimal itemValINSS;
        @XmlElement(name = "ItemValAliqIR")
        protected BigDecimal itemValAliqIR;
        @XmlElement(name = "ItemValIR")
        protected BigDecimal itemValIR;
        @XmlElement(name = "ItemValAliqCOFINS")
        protected BigDecimal itemValAliqCOFINS;
        @XmlElement(name = "ItemValCOFINS")
        protected BigDecimal itemValCOFINS;
        @XmlElement(name = "ItemValAliqCSLL")
        protected BigDecimal itemValAliqCSLL;
        @XmlElement(name = "ItemValCSLL")
        protected BigDecimal itemValCSLL;
        @XmlElement(name = "ItemValAliqPIS ")
        protected BigDecimal itemValAliqPIS0020;
        @XmlElement(name = "ItemValPIS")
        protected BigDecimal itemValPIS;
        @XmlElement(name = "ItemRedBCRetido")
        protected BigDecimal itemRedBCRetido;
        @XmlElement(name = "ItemBCRetido")
        protected BigDecimal itemBCRetido;
        @XmlElement(name = "ItemPaisImpDevido")
        protected String itemPaisImpDevido;
        @XmlElement(name = "ItemValAliqISSRetido")
        protected BigDecimal itemValAliqISSRetido;
        @XmlElement(name = "ItemJustDed")
        protected String itemJustDed;
        @XmlElement(name = "ItemvOutrasRetencoes")
        protected BigDecimal itemvOutrasRetencoes;
        @XmlElement(name = "ItemDescIncondicionado")
        protected BigDecimal itemDescIncondicionado;
        @XmlElement(name = "ItemDescCondicionado")
        protected BigDecimal itemDescCondicionado;

        /**
         * Gets the value of the itemSeq property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getItemSeq() {
            return itemSeq;
        }

        /**
         * Sets the value of the itemSeq property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setItemSeq(BigInteger value) {
            this.itemSeq = value;
        }

        /**
         * Gets the value of the itemCod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemCod() {
            return itemCod;
        }

        /**
         * Sets the value of the itemCod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemCod(String value) {
            this.itemCod = value;
        }

        /**
         * Gets the value of the itemDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemDesc() {
            return itemDesc;
        }

        /**
         * Sets the value of the itemDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemDesc(String value) {
            this.itemDesc = value;
        }

        /**
         * Gets the value of the itemQtde property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemQtde() {
            return itemQtde;
        }

        /**
         * Sets the value of the itemQtde property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemQtde(BigDecimal value) {
            this.itemQtde = value;
        }

        /**
         * Gets the value of the itemvUnit property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemvUnit() {
            return itemvUnit;
        }

        /**
         * Sets the value of the itemvUnit property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemvUnit(BigDecimal value) {
            this.itemvUnit = value;
        }

        /**
         * Gets the value of the itemuMed property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemuMed() {
            return itemuMed;
        }

        /**
         * Sets the value of the itemuMed property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemuMed(String value) {
            this.itemuMed = value;
        }

        /**
         * Gets the value of the itemvlDed property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemvlDed() {
            return itemvlDed;
        }

        /**
         * Sets the value of the itemvlDed property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemvlDed(BigDecimal value) {
            this.itemvlDed = value;
        }

        /**
         * Gets the value of the itemTributavel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemTributavel() {
            return itemTributavel;
        }

        /**
         * Sets the value of the itemTributavel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemTributavel(String value) {
            this.itemTributavel = value;
        }

        /**
         * Gets the value of the itemcCnae property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getItemcCnae() {
            return itemcCnae;
        }

        /**
         * Sets the value of the itemcCnae property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setItemcCnae(BigInteger value) {
            this.itemcCnae = value;
        }

        /**
         * Gets the value of the itemTributMunicipio property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemTributMunicipio() {
            return itemTributMunicipio;
        }

        /**
         * Sets the value of the itemTributMunicipio property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemTributMunicipio(String value) {
            this.itemTributMunicipio = value;
        }

        /**
         * Gets the value of the itemnAlvara property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemnAlvara() {
            return itemnAlvara;
        }

        /**
         * Sets the value of the itemnAlvara property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemnAlvara(String value) {
            this.itemnAlvara = value;
        }

        /**
         * Gets the value of the itemvIss property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemvIss() {
            return itemvIss;
        }

        /**
         * Sets the value of the itemvIss property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemvIss(BigDecimal value) {
            this.itemvIss = value;
        }

        /**
         * Gets the value of the itemvDesconto property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemvDesconto() {
            return itemvDesconto;
        }

        /**
         * Sets the value of the itemvDesconto property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemvDesconto(BigDecimal value) {
            this.itemvDesconto = value;
        }

        /**
         * Gets the value of the itemAliquota property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemAliquota() {
            return itemAliquota;
        }

        /**
         * Sets the value of the itemAliquota property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemAliquota(BigDecimal value) {
            this.itemAliquota = value;
        }

        /**
         * Gets the value of the itemVlrTotal property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemVlrTotal() {
            return itemVlrTotal;
        }

        /**
         * Sets the value of the itemVlrTotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemVlrTotal(BigDecimal value) {
            this.itemVlrTotal = value;
        }

        /**
         * Gets the value of the itemBaseCalculo property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemBaseCalculo() {
            return itemBaseCalculo;
        }

        /**
         * Sets the value of the itemBaseCalculo property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemBaseCalculo(BigDecimal value) {
            this.itemBaseCalculo = value;
        }

        /**
         * Gets the value of the itemvlrISSRetido property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemvlrISSRetido() {
            return itemvlrISSRetido;
        }

        /**
         * Sets the value of the itemvlrISSRetido property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemvlrISSRetido(BigDecimal value) {
            this.itemvlrISSRetido = value;
        }

        /**
         * Gets the value of the itemIssRetido property.
         * 
         */
        public int getItemIssRetido() {
            return itemIssRetido;
        }

        /**
         * Sets the value of the itemIssRetido property.
         * 
         */
        public void setItemIssRetido(int value) {
            this.itemIssRetido = value;
        }

        /**
         * Gets the value of the itemRespRetencao property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getItemRespRetencao() {
            return itemRespRetencao;
        }

        /**
         * Sets the value of the itemRespRetencao property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setItemRespRetencao(Integer value) {
            this.itemRespRetencao = value;
        }

        /**
         * Gets the value of the itemIteListServico property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemIteListServico() {
            return itemIteListServico;
        }

        /**
         * Sets the value of the itemIteListServico property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemIteListServico(String value) {
            this.itemIteListServico = value;
        }

        /**
         * Gets the value of the itemExigibilidadeISS property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getItemExigibilidadeISS() {
            return itemExigibilidadeISS;
        }

        /**
         * Sets the value of the itemExigibilidadeISS property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setItemExigibilidadeISS(BigInteger value) {
            this.itemExigibilidadeISS = value;
        }

        /**
         * Gets the value of the itemcMunIncidencia property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getItemcMunIncidencia() {
            return itemcMunIncidencia;
        }

        /**
         * Sets the value of the itemcMunIncidencia property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setItemcMunIncidencia(BigInteger value) {
            this.itemcMunIncidencia = value;
        }

        /**
         * Gets the value of the itemNumProcesso property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemNumProcesso() {
            return itemNumProcesso;
        }

        /**
         * Sets the value of the itemNumProcesso property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemNumProcesso(String value) {
            this.itemNumProcesso = value;
        }

        /**
         * Gets the value of the itemDedTipo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemDedTipo() {
            return itemDedTipo;
        }

        /**
         * Sets the value of the itemDedTipo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemDedTipo(String value) {
            this.itemDedTipo = value;
        }

        /**
         * Gets the value of the itemDedCPFRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemDedCPFRef() {
            return itemDedCPFRef;
        }

        /**
         * Sets the value of the itemDedCPFRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemDedCPFRef(String value) {
            this.itemDedCPFRef = value;
        }

        /**
         * Gets the value of the itemDedCNPJRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemDedCNPJRef() {
            return itemDedCNPJRef;
        }

        /**
         * Sets the value of the itemDedCNPJRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemDedCNPJRef(String value) {
            this.itemDedCNPJRef = value;
        }

        /**
         * Gets the value of the itemDedNFRef property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getItemDedNFRef() {
            return itemDedNFRef;
        }

        /**
         * Sets the value of the itemDedNFRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setItemDedNFRef(BigInteger value) {
            this.itemDedNFRef = value;
        }

        /**
         * Gets the value of the itemDedvlTotRef property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemDedvlTotRef() {
            return itemDedvlTotRef;
        }

        /**
         * Sets the value of the itemDedvlTotRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemDedvlTotRef(BigDecimal value) {
            this.itemDedvlTotRef = value;
        }

        /**
         * Gets the value of the itemDedPer property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemDedPer() {
            return itemDedPer;
        }

        /**
         * Sets the value of the itemDedPer property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemDedPer(BigDecimal value) {
            this.itemDedPer = value;
        }

        /**
         * Gets the value of the itemVlrLiquido property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemVlrLiquido() {
            return itemVlrLiquido;
        }

        /**
         * Sets the value of the itemVlrLiquido property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemVlrLiquido(BigDecimal value) {
            this.itemVlrLiquido = value;
        }

        /**
         * Gets the value of the itemValAliqINSS property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemValAliqINSS() {
            return itemValAliqINSS;
        }

        /**
         * Sets the value of the itemValAliqINSS property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemValAliqINSS(BigDecimal value) {
            this.itemValAliqINSS = value;
        }

        /**
         * Gets the value of the itemValINSS property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemValINSS() {
            return itemValINSS;
        }

        /**
         * Sets the value of the itemValINSS property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemValINSS(BigDecimal value) {
            this.itemValINSS = value;
        }

        /**
         * Gets the value of the itemValAliqIR property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemValAliqIR() {
            return itemValAliqIR;
        }

        /**
         * Sets the value of the itemValAliqIR property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemValAliqIR(BigDecimal value) {
            this.itemValAliqIR = value;
        }

        /**
         * Gets the value of the itemValIR property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemValIR() {
            return itemValIR;
        }

        /**
         * Sets the value of the itemValIR property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemValIR(BigDecimal value) {
            this.itemValIR = value;
        }

        /**
         * Gets the value of the itemValAliqCOFINS property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemValAliqCOFINS() {
            return itemValAliqCOFINS;
        }

        /**
         * Sets the value of the itemValAliqCOFINS property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemValAliqCOFINS(BigDecimal value) {
            this.itemValAliqCOFINS = value;
        }

        /**
         * Gets the value of the itemValCOFINS property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemValCOFINS() {
            return itemValCOFINS;
        }

        /**
         * Sets the value of the itemValCOFINS property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemValCOFINS(BigDecimal value) {
            this.itemValCOFINS = value;
        }

        /**
         * Gets the value of the itemValAliqCSLL property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemValAliqCSLL() {
            return itemValAliqCSLL;
        }

        /**
         * Sets the value of the itemValAliqCSLL property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemValAliqCSLL(BigDecimal value) {
            this.itemValAliqCSLL = value;
        }

        /**
         * Gets the value of the itemValCSLL property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemValCSLL() {
            return itemValCSLL;
        }

        /**
         * Sets the value of the itemValCSLL property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemValCSLL(BigDecimal value) {
            this.itemValCSLL = value;
        }

        /**
         * Gets the value of the itemValAliqPIS0020 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemValAliqPIS_0020() {
            return itemValAliqPIS0020;
        }

        /**
         * Sets the value of the itemValAliqPIS0020 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemValAliqPIS_0020(BigDecimal value) {
            this.itemValAliqPIS0020 = value;
        }

        /**
         * Gets the value of the itemValPIS property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemValPIS() {
            return itemValPIS;
        }

        /**
         * Sets the value of the itemValPIS property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemValPIS(BigDecimal value) {
            this.itemValPIS = value;
        }

        /**
         * Gets the value of the itemRedBCRetido property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemRedBCRetido() {
            return itemRedBCRetido;
        }

        /**
         * Sets the value of the itemRedBCRetido property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemRedBCRetido(BigDecimal value) {
            this.itemRedBCRetido = value;
        }

        /**
         * Gets the value of the itemBCRetido property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemBCRetido() {
            return itemBCRetido;
        }

        /**
         * Sets the value of the itemBCRetido property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemBCRetido(BigDecimal value) {
            this.itemBCRetido = value;
        }

        /**
         * Gets the value of the itemPaisImpDevido property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemPaisImpDevido() {
            return itemPaisImpDevido;
        }

        /**
         * Sets the value of the itemPaisImpDevido property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemPaisImpDevido(String value) {
            this.itemPaisImpDevido = value;
        }

        /**
         * Gets the value of the itemValAliqISSRetido property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemValAliqISSRetido() {
            return itemValAliqISSRetido;
        }

        /**
         * Sets the value of the itemValAliqISSRetido property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemValAliqISSRetido(BigDecimal value) {
            this.itemValAliqISSRetido = value;
        }

        /**
         * Gets the value of the itemJustDed property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemJustDed() {
            return itemJustDed;
        }

        /**
         * Sets the value of the itemJustDed property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemJustDed(String value) {
            this.itemJustDed = value;
        }

        /**
         * Gets the value of the itemvOutrasRetencoes property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemvOutrasRetencoes() {
            return itemvOutrasRetencoes;
        }

        /**
         * Sets the value of the itemvOutrasRetencoes property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemvOutrasRetencoes(BigDecimal value) {
            this.itemvOutrasRetencoes = value;
        }

        /**
         * Gets the value of the itemDescIncondicionado property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemDescIncondicionado() {
            return itemDescIncondicionado;
        }

        /**
         * Sets the value of the itemDescIncondicionado property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemDescIncondicionado(BigDecimal value) {
            this.itemDescIncondicionado = value;
        }

        /**
         * Gets the value of the itemDescCondicionado property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemDescCondicionado() {
            return itemDescCondicionado;
        }

        /**
         * Sets the value of the itemDescCondicionado property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemDescCondicionado(BigDecimal value) {
            this.itemDescCondicionado = value;
        }

    }

}
