//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.29 at 01:58:16 PM ART 
//


package br.inf.portalfiscal.nfse;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SerEndTpLgr"/>
 *         &lt;element ref="{}SerEndLgr"/>
 *         &lt;element ref="{}SerEndNumero"/>
 *         &lt;element ref="{}SerEndComplemento"/>
 *         &lt;element ref="{}SerEndBairro"/>
 *         &lt;element ref="{}SerEndxMun"/>
 *         &lt;element ref="{}SerEndcMun"/>
 *         &lt;element ref="{}SerEndCep"/>
 *         &lt;element ref="{}SerEndSiglaUF"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "serEndTpLgr",
    "serEndLgr",
    "serEndNumero",
    "serEndComplemento",
    "serEndBairro",
    "serEndxMun",
    "serEndcMun",
    "serEndCep",
    "serEndSiglaUF"
})
@XmlRootElement(name = "LocalPrestacao")
public class LocalPrestacao {

    @XmlElement(name = "SerEndTpLgr", required = true)
    protected String serEndTpLgr;
    @XmlElement(name = "SerEndLgr", required = true)
    protected String serEndLgr;
    @XmlElement(name = "SerEndNumero", required = true)
    protected String serEndNumero;
    @XmlElement(name = "SerEndComplemento", required = true)
    protected String serEndComplemento;
    @XmlElement(name = "SerEndBairro", required = true)
    protected String serEndBairro;
    @XmlElement(name = "SerEndxMun", required = true)
    protected String serEndxMun;
    @XmlElement(name = "SerEndcMun", required = true)
    protected BigInteger serEndcMun;
    @XmlElement(name = "SerEndCep", required = true)
    protected BigInteger serEndCep;
    @XmlElement(name = "SerEndSiglaUF", required = true)
    protected String serEndSiglaUF;

    /**
     * Gets the value of the serEndTpLgr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerEndTpLgr() {
        return serEndTpLgr;
    }

    /**
     * Sets the value of the serEndTpLgr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerEndTpLgr(String value) {
        this.serEndTpLgr = value;
    }

    /**
     * Gets the value of the serEndLgr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerEndLgr() {
        return serEndLgr;
    }

    /**
     * Sets the value of the serEndLgr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerEndLgr(String value) {
        this.serEndLgr = value;
    }

    /**
     * Gets the value of the serEndNumero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerEndNumero() {
        return serEndNumero;
    }

    /**
     * Sets the value of the serEndNumero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerEndNumero(String value) {
        this.serEndNumero = value;
    }

    /**
     * Gets the value of the serEndComplemento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerEndComplemento() {
        return serEndComplemento;
    }

    /**
     * Sets the value of the serEndComplemento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerEndComplemento(String value) {
        this.serEndComplemento = value;
    }

    /**
     * Gets the value of the serEndBairro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerEndBairro() {
        return serEndBairro;
    }

    /**
     * Sets the value of the serEndBairro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerEndBairro(String value) {
        this.serEndBairro = value;
    }

    /**
     * Gets the value of the serEndxMun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerEndxMun() {
        return serEndxMun;
    }

    /**
     * Sets the value of the serEndxMun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerEndxMun(String value) {
        this.serEndxMun = value;
    }

    /**
     * Gets the value of the serEndcMun property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSerEndcMun() {
        return serEndcMun;
    }

    /**
     * Sets the value of the serEndcMun property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSerEndcMun(BigInteger value) {
        this.serEndcMun = value;
    }

    /**
     * Gets the value of the serEndCep property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSerEndCep() {
        return serEndCep;
    }

    /**
     * Sets the value of the serEndCep property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSerEndCep(BigInteger value) {
        this.serEndCep = value;
    }

    /**
     * Gets the value of the serEndSiglaUF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerEndSiglaUF() {
        return serEndSiglaUF;
    }

    /**
     * Sets the value of the serEndSiglaUF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerEndSiglaUF(String value) {
        this.serEndSiglaUF = value;
    }

}
