//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.29 at 01:58:16 PM ART 
//


package br.inf.portalfiscal.nfse;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}MatCodigo" minOccurs="0"/>
 *         &lt;element ref="{}MatDescricao" minOccurs="0"/>
 *         &lt;element ref="{}MatUndMedCodigo" minOccurs="0"/>
 *         &lt;element ref="{}MatUndMedSigla" minOccurs="0"/>
 *         &lt;element ref="{}MatQuantidade" minOccurs="0"/>
 *         &lt;element ref="{}MatVlrTotal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "matCodigo",
    "matDescricao",
    "matUndMedCodigo",
    "matUndMedSigla",
    "matQuantidade",
    "matVlrTotal"
})
@XmlRootElement(name = "Material")
public class Material {

    @XmlElement(name = "MatCodigo")
    protected String matCodigo;
    @XmlElement(name = "MatDescricao")
    protected String matDescricao;
    @XmlElement(name = "MatUndMedCodigo")
    protected String matUndMedCodigo;
    @XmlElement(name = "MatUndMedSigla")
    protected String matUndMedSigla;
    @XmlElement(name = "MatQuantidade")
    protected BigInteger matQuantidade;
    @XmlElement(name = "MatVlrTotal")
    protected BigDecimal matVlrTotal;

    /**
     * Gets the value of the matCodigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatCodigo() {
        return matCodigo;
    }

    /**
     * Sets the value of the matCodigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatCodigo(String value) {
        this.matCodigo = value;
    }

    /**
     * Gets the value of the matDescricao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatDescricao() {
        return matDescricao;
    }

    /**
     * Sets the value of the matDescricao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatDescricao(String value) {
        this.matDescricao = value;
    }

    /**
     * Gets the value of the matUndMedCodigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatUndMedCodigo() {
        return matUndMedCodigo;
    }

    /**
     * Sets the value of the matUndMedCodigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatUndMedCodigo(String value) {
        this.matUndMedCodigo = value;
    }

    /**
     * Gets the value of the matUndMedSigla property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatUndMedSigla() {
        return matUndMedSigla;
    }

    /**
     * Sets the value of the matUndMedSigla property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatUndMedSigla(String value) {
        this.matUndMedSigla = value;
    }

    /**
     * Gets the value of the matQuantidade property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMatQuantidade() {
        return matQuantidade;
    }

    /**
     * Sets the value of the matQuantidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMatQuantidade(BigInteger value) {
        this.matQuantidade = value;
    }

    /**
     * Gets the value of the matVlrTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMatVlrTotal() {
        return matVlrTotal;
    }

    /**
     * Sets the value of the matVlrTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMatVlrTotal(BigDecimal value) {
        this.matVlrTotal = value;
    }

}
