//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.29 at 01:58:16 PM ART 
//


package br.inf.portalfiscal.nfse;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CNPJ_prest"/>
 *         &lt;element ref="{}CPF_prest"/>
 *         &lt;element ref="{}xNome"/>
 *         &lt;element ref="{}xFant"/>
 *         &lt;element ref="{}IM"/>
 *         &lt;element ref="{}IE" minOccurs="0"/>
 *         &lt;element ref="{}CMC" minOccurs="0"/>
 *         &lt;element ref="{}enderPrest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cnpjPrest",
    "cpfPrest",
    "xNome",
    "xFant",
    "im",
    "ie",
    "cmc",
    "enderPrest"
})
@XmlRootElement(name = "Prestador")
public class Prestador {

    @XmlElement(name = "CNPJ_prest", required = true)
    protected String cnpjPrest;
    @XmlElement(name = "CPF_prest", required = true)
    protected String cpfPrest;
    @XmlElement(required = true)
    protected String xNome;
    @XmlElement(required = true)
    protected String xFant;
    @XmlElement(name = "IM", required = true)
    protected String im;
    @XmlElement(name = "IE")
    protected String ie;
    @XmlElement(name = "CMC")
    protected BigInteger cmc;
    @XmlElement(required = true)
    protected EnderPrest enderPrest;

    /**
     * Gets the value of the cnpjPrest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNPJPrest() {
        return cnpjPrest;
    }

    /**
     * Sets the value of the cnpjPrest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNPJPrest(String value) {
        this.cnpjPrest = value;
    }

    /**
     * Gets the value of the cpfPrest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPFPrest() {
        return cpfPrest;
    }

    /**
     * Sets the value of the cpfPrest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPFPrest(String value) {
        this.cpfPrest = value;
    }

    /**
     * Gets the value of the xNome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXNome() {
        return xNome;
    }

    /**
     * Sets the value of the xNome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXNome(String value) {
        this.xNome = value;
    }

    /**
     * Gets the value of the xFant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXFant() {
        return xFant;
    }

    /**
     * Sets the value of the xFant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXFant(String value) {
        this.xFant = value;
    }

    /**
     * Gets the value of the im property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIM() {
        return im;
    }

    /**
     * Sets the value of the im property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIM(String value) {
        this.im = value;
    }

    /**
     * Gets the value of the ie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIE() {
        return ie;
    }

    /**
     * Sets the value of the ie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIE(String value) {
        this.ie = value;
    }

    /**
     * Gets the value of the cmc property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCMC() {
        return cmc;
    }

    /**
     * Sets the value of the cmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCMC(BigInteger value) {
        this.cmc = value;
    }

    /**
     * Gets the value of the enderPrest property.
     * 
     * @return
     *     possible object is
     *     {@link EnderPrest }
     *     
     */
    public EnderPrest getEnderPrest() {
        return enderPrest;
    }

    /**
     * Sets the value of the enderPrest property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnderPrest }
     *     
     */
    public void setEnderPrest(EnderPrest value) {
        this.enderPrest = value;
    }

}
