//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.29 at 01:58:16 PM ART 
//


package br.inf.portalfiscal.nfse;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}RPSNumero"/>
 *         &lt;element ref="{}RPSSerie"/>
 *         &lt;element ref="{}RPSTipo"/>
 *         &lt;element ref="{}dEmis"/>
 *         &lt;element ref="{}dCompetencia" minOccurs="0"/>
 *         &lt;element ref="{}LocalPrestServ" minOccurs="0"/>
 *         &lt;element ref="{}natOp"/>
 *         &lt;element ref="{}Operacao"/>
 *         &lt;element ref="{}NumProcesso" minOccurs="0"/>
 *         &lt;element ref="{}RegEspTrib" minOccurs="0"/>
 *         &lt;element ref="{}OptSN"/>
 *         &lt;element ref="{}IncCult"/>
 *         &lt;element ref="{}Status"/>
 *         &lt;element ref="{}cVerificaRPS" minOccurs="0"/>
 *         &lt;element ref="{}EmpreitadaGlobal" minOccurs="0"/>
 *         &lt;element ref="{}tpAmb"/>
 *         &lt;element ref="{}RPSSubs" minOccurs="0"/>
 *         &lt;element ref="{}Prestador"/>
 *         &lt;element ref="{}ListaItens" minOccurs="0"/>
 *         &lt;element ref="{}ListaParcelas" minOccurs="0"/>
 *         &lt;element ref="{}Servico"/>
 *         &lt;element ref="{}Tomador" minOccurs="0"/>
 *         &lt;element ref="{}IntermServico" minOccurs="0"/>
 *         &lt;element ref="{}ConstCivil" minOccurs="0"/>
 *         &lt;element ref="{}ListaDed" minOccurs="0"/>
 *         &lt;element ref="{}Transportadora" minOccurs="0"/>
 *         &lt;element ref="{}NFSOutrasinformacoes" minOccurs="0"/>
 *         &lt;element ref="{}RPSCanhoto" minOccurs="0"/>
 *         &lt;element ref="{}Arquivo" minOccurs="0"/>
 *         &lt;element ref="{}ExtensaoArquivo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rpsNumero",
    "rpsSerie",
    "rpsTipo",
    "dEmis",
    "dCompetencia",
    "localPrestServ",
    "natOp",
    "operacao",
    "numProcesso",
    "regEspTrib",
    "optSN",
    "incCult",
    "status",
    "cVerificaRPS",
    "empreitadaGlobal",
    "tpAmb",
    "rpsSubs",
    "prestador",
    "listaItens",
    "listaParcelas",
    "servico",
    "tomador",
    "intermServico",
    "constCivil",
    "listaDed",
    "transportadora",
    "nfsOutrasinformacoes",
    "rpsCanhoto",
    "arquivo",
    "extensaoArquivo"
})
@XmlRootElement(name = "RPS")
public class RPS {

    @XmlElement(name = "RPSNumero", required = true)
    protected BigInteger rpsNumero;
    @XmlElement(name = "RPSSerie", required = true)
    protected String rpsSerie;
    @XmlElement(name = "RPSTipo", required = true)
    protected BigInteger rpsTipo;
    @XmlElement(required = true)
    protected XMLGregorianCalendar dEmis;
    protected XMLGregorianCalendar dCompetencia;
    @XmlElement(name = "LocalPrestServ")
    protected Integer localPrestServ;
    @XmlElement(required = true)
    protected BigInteger natOp;
    @XmlElement(name = "Operacao", required = true)
    protected String operacao;
    @XmlElement(name = "NumProcesso")
    protected String numProcesso;
    @XmlElement(name = "RegEspTrib")
    protected Integer regEspTrib;
    @XmlElement(name = "OptSN")
    protected int optSN;
    @XmlElement(name = "IncCult")
    protected int incCult;
    @XmlElement(name = "Status")
    protected int status;
    protected String cVerificaRPS;
    @XmlElement(name = "EmpreitadaGlobal")
    protected BigInteger empreitadaGlobal;
    protected int tpAmb;
    @XmlElement(name = "RPSSubs")
    protected RPSSubs rpsSubs;
    @XmlElement(name = "Prestador", required = true)
    protected Prestador prestador;
    @XmlElement(name = "ListaItens")
    protected ListaItens listaItens;
    @XmlElement(name = "ListaParcelas")
    protected ListaParcelas listaParcelas;
    @XmlElement(name = "Servico", required = true)
    protected Servico servico;
    @XmlElement(name = "Tomador")
    protected Tomador tomador;
    @XmlElement(name = "IntermServico")
    protected IntermServico intermServico;
    @XmlElement(name = "ConstCivil")
    protected ConstCivil constCivil;
    @XmlElement(name = "ListaDed")
    protected ListaDed listaDed;
    @XmlElement(name = "Transportadora")
    protected Transportadora transportadora;
    @XmlElement(name = "NFSOutrasinformacoes")
    protected String nfsOutrasinformacoes;
    @XmlElement(name = "RPSCanhoto")
    protected BigInteger rpsCanhoto;
    @XmlElement(name = "Arquivo")
    protected String arquivo;
    @XmlElement(name = "ExtensaoArquivo")
    protected String extensaoArquivo;

    /**
     * Gets the value of the rpsNumero property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRPSNumero() {
        return rpsNumero;
    }

    /**
     * Sets the value of the rpsNumero property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRPSNumero(BigInteger value) {
        this.rpsNumero = value;
    }

    /**
     * Gets the value of the rpsSerie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRPSSerie() {
        return rpsSerie;
    }

    /**
     * Sets the value of the rpsSerie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRPSSerie(String value) {
        this.rpsSerie = value;
    }

    /**
     * Gets the value of the rpsTipo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRPSTipo() {
        return rpsTipo;
    }

    /**
     * Sets the value of the rpsTipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRPSTipo(BigInteger value) {
        this.rpsTipo = value;
    }

    /**
     * Gets the value of the dEmis property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDEmis() {
        return dEmis;
    }

    /**
     * Sets the value of the dEmis property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDEmis(XMLGregorianCalendar value) {
        this.dEmis = value;
    }

    /**
     * Gets the value of the dCompetencia property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDCompetencia() {
        return dCompetencia;
    }

    /**
     * Sets the value of the dCompetencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDCompetencia(XMLGregorianCalendar value) {
        this.dCompetencia = value;
    }

    /**
     * Gets the value of the localPrestServ property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLocalPrestServ() {
        return localPrestServ;
    }

    /**
     * Sets the value of the localPrestServ property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLocalPrestServ(Integer value) {
        this.localPrestServ = value;
    }

    /**
     * Gets the value of the natOp property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNatOp() {
        return natOp;
    }

    /**
     * Sets the value of the natOp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNatOp(BigInteger value) {
        this.natOp = value;
    }

    /**
     * Gets the value of the operacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperacao() {
        return operacao;
    }

    /**
     * Sets the value of the operacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperacao(String value) {
        this.operacao = value;
    }

    /**
     * Gets the value of the numProcesso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumProcesso() {
        return numProcesso;
    }

    /**
     * Sets the value of the numProcesso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumProcesso(String value) {
        this.numProcesso = value;
    }

    /**
     * Gets the value of the regEspTrib property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRegEspTrib() {
        return regEspTrib;
    }

    /**
     * Sets the value of the regEspTrib property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRegEspTrib(Integer value) {
        this.regEspTrib = value;
    }

    /**
     * Gets the value of the optSN property.
     * 
     */
    public int getOptSN() {
        return optSN;
    }

    /**
     * Sets the value of the optSN property.
     * 
     */
    public void setOptSN(int value) {
        this.optSN = value;
    }

    /**
     * Gets the value of the incCult property.
     * 
     */
    public int getIncCult() {
        return incCult;
    }

    /**
     * Sets the value of the incCult property.
     * 
     */
    public void setIncCult(int value) {
        this.incCult = value;
    }

    /**
     * Gets the value of the status property.
     * 
     */
    public int getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     */
    public void setStatus(int value) {
        this.status = value;
    }

    /**
     * Gets the value of the cVerificaRPS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCVerificaRPS() {
        return cVerificaRPS;
    }

    /**
     * Sets the value of the cVerificaRPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCVerificaRPS(String value) {
        this.cVerificaRPS = value;
    }

    /**
     * Gets the value of the empreitadaGlobal property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEmpreitadaGlobal() {
        return empreitadaGlobal;
    }

    /**
     * Sets the value of the empreitadaGlobal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEmpreitadaGlobal(BigInteger value) {
        this.empreitadaGlobal = value;
    }

    /**
     * Gets the value of the tpAmb property.
     * 
     */
    public int getTpAmb() {
        return tpAmb;
    }

    /**
     * Sets the value of the tpAmb property.
     * 
     */
    public void setTpAmb(int value) {
        this.tpAmb = value;
    }

    /**
     * Gets the value of the rpsSubs property.
     * 
     * @return
     *     possible object is
     *     {@link RPSSubs }
     *     
     */
    public RPSSubs getRPSSubs() {
        return rpsSubs;
    }

    /**
     * Sets the value of the rpsSubs property.
     * 
     * @param value
     *     allowed object is
     *     {@link RPSSubs }
     *     
     */
    public void setRPSSubs(RPSSubs value) {
        this.rpsSubs = value;
    }

    /**
     * Gets the value of the prestador property.
     * 
     * @return
     *     possible object is
     *     {@link Prestador }
     *     
     */
    public Prestador getPrestador() {
        return prestador;
    }

    /**
     * Sets the value of the prestador property.
     * 
     * @param value
     *     allowed object is
     *     {@link Prestador }
     *     
     */
    public void setPrestador(Prestador value) {
        this.prestador = value;
    }

    /**
     * Gets the value of the listaItens property.
     * 
     * @return
     *     possible object is
     *     {@link ListaItens }
     *     
     */
    public ListaItens getListaItens() {
        return listaItens;
    }

    /**
     * Sets the value of the listaItens property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListaItens }
     *     
     */
    public void setListaItens(ListaItens value) {
        this.listaItens = value;
    }

    /**
     * Gets the value of the listaParcelas property.
     * 
     * @return
     *     possible object is
     *     {@link ListaParcelas }
     *     
     */
    public ListaParcelas getListaParcelas() {
        return listaParcelas;
    }

    /**
     * Sets the value of the listaParcelas property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListaParcelas }
     *     
     */
    public void setListaParcelas(ListaParcelas value) {
        this.listaParcelas = value;
    }

    /**
     * Gets the value of the servico property.
     * 
     * @return
     *     possible object is
     *     {@link Servico }
     *     
     */
    public Servico getServico() {
        return servico;
    }

    /**
     * Sets the value of the servico property.
     * 
     * @param value
     *     allowed object is
     *     {@link Servico }
     *     
     */
    public void setServico(Servico value) {
        this.servico = value;
    }

    /**
     * Gets the value of the tomador property.
     * 
     * @return
     *     possible object is
     *     {@link Tomador }
     *     
     */
    public Tomador getTomador() {
        return tomador;
    }

    /**
     * Sets the value of the tomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tomador }
     *     
     */
    public void setTomador(Tomador value) {
        this.tomador = value;
    }

    /**
     * Gets the value of the intermServico property.
     * 
     * @return
     *     possible object is
     *     {@link IntermServico }
     *     
     */
    public IntermServico getIntermServico() {
        return intermServico;
    }

    /**
     * Sets the value of the intermServico property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntermServico }
     *     
     */
    public void setIntermServico(IntermServico value) {
        this.intermServico = value;
    }

    /**
     * Gets the value of the constCivil property.
     * 
     * @return
     *     possible object is
     *     {@link ConstCivil }
     *     
     */
    public ConstCivil getConstCivil() {
        return constCivil;
    }

    /**
     * Sets the value of the constCivil property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstCivil }
     *     
     */
    public void setConstCivil(ConstCivil value) {
        this.constCivil = value;
    }

    /**
     * Gets the value of the listaDed property.
     * 
     * @return
     *     possible object is
     *     {@link ListaDed }
     *     
     */
    public ListaDed getListaDed() {
        return listaDed;
    }

    /**
     * Sets the value of the listaDed property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListaDed }
     *     
     */
    public void setListaDed(ListaDed value) {
        this.listaDed = value;
    }

    /**
     * Gets the value of the transportadora property.
     * 
     * @return
     *     possible object is
     *     {@link Transportadora }
     *     
     */
    public Transportadora getTransportadora() {
        return transportadora;
    }

    /**
     * Sets the value of the transportadora property.
     * 
     * @param value
     *     allowed object is
     *     {@link Transportadora }
     *     
     */
    public void setTransportadora(Transportadora value) {
        this.transportadora = value;
    }

    /**
     * Gets the value of the nfsOutrasinformacoes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNFSOutrasinformacoes() {
        return nfsOutrasinformacoes;
    }

    /**
     * Sets the value of the nfsOutrasinformacoes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNFSOutrasinformacoes(String value) {
        this.nfsOutrasinformacoes = value;
    }

    /**
     * Gets the value of the rpsCanhoto property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRPSCanhoto() {
        return rpsCanhoto;
    }

    /**
     * Sets the value of the rpsCanhoto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRPSCanhoto(BigInteger value) {
        this.rpsCanhoto = value;
    }

    /**
     * Gets the value of the arquivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArquivo() {
        return arquivo;
    }

    /**
     * Sets the value of the arquivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArquivo(String value) {
        this.arquivo = value;
    }

    /**
     * Gets the value of the extensaoArquivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtensaoArquivo() {
        return extensaoArquivo;
    }

    /**
     * Sets the value of the extensaoArquivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtensaoArquivo(String value) {
        this.extensaoArquivo = value;
    }

}
