//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.29 at 01:58:16 PM ART 
//


package br.inf.portalfiscal.nfse;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SubsNumero"/>
 *         &lt;element ref="{}SubsSerie"/>
 *         &lt;element ref="{}SubsTipo"/>
 *         &lt;element ref="{}SubsNFSeNumero" minOccurs="0"/>
 *         &lt;element ref="{}SubsDEmisNFSe" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subsNumero",
    "subsSerie",
    "subsTipo",
    "subsNFSeNumero",
    "subsDEmisNFSe"
})
@XmlRootElement(name = "RPSSubs")
public class RPSSubs {

    @XmlElement(name = "SubsNumero", required = true)
    protected BigInteger subsNumero;
    @XmlElement(name = "SubsSerie", required = true)
    protected String subsSerie;
    @XmlElement(name = "SubsTipo", required = true)
    protected BigInteger subsTipo;
    @XmlElement(name = "SubsNFSeNumero")
    protected BigInteger subsNFSeNumero;
    @XmlElement(name = "SubsDEmisNFSe")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar subsDEmisNFSe;

    /**
     * Gets the value of the subsNumero property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSubsNumero() {
        return subsNumero;
    }

    /**
     * Sets the value of the subsNumero property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSubsNumero(BigInteger value) {
        this.subsNumero = value;
    }

    /**
     * Gets the value of the subsSerie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubsSerie() {
        return subsSerie;
    }

    /**
     * Sets the value of the subsSerie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubsSerie(String value) {
        this.subsSerie = value;
    }

    /**
     * Gets the value of the subsTipo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSubsTipo() {
        return subsTipo;
    }

    /**
     * Sets the value of the subsTipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSubsTipo(BigInteger value) {
        this.subsTipo = value;
    }

    /**
     * Gets the value of the subsNFSeNumero property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSubsNFSeNumero() {
        return subsNFSeNumero;
    }

    /**
     * Sets the value of the subsNFSeNumero property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSubsNFSeNumero(BigInteger value) {
        this.subsNFSeNumero = value;
    }

    /**
     * Gets the value of the subsDEmisNFSe property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSubsDEmisNFSe() {
        return subsDEmisNFSe;
    }

    /**
     * Sets the value of the subsDEmisNFSe property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSubsDEmisNFSe(XMLGregorianCalendar value) {
        this.subsDEmisNFSe = value;
    }

}
