//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.29 at 01:58:16 PM ART 
//


package br.inf.portalfiscal.nfse;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Valores"/>
 *         &lt;element ref="{}LocalPrestacao" minOccurs="0"/>
 *         &lt;element ref="{}IteListServico"/>
 *         &lt;element ref="{}Cnae" minOccurs="0"/>
 *         &lt;element ref="{}fPagamento" minOccurs="0"/>
 *         &lt;element ref="{}TributMunicipio"/>
 *         &lt;element ref="{}TributMunicDesc" minOccurs="0"/>
 *         &lt;element ref="{}Discriminacao"/>
 *         &lt;element ref="{}cMun"/>
 *         &lt;element ref="{}SerQuantidade" minOccurs="0"/>
 *         &lt;element ref="{}SerUnidade" minOccurs="0"/>
 *         &lt;element ref="{}SerNumAlva" minOccurs="0"/>
 *         &lt;element ref="{}PaiPreServico" minOccurs="0"/>
 *         &lt;element ref="{}cMunIncidencia" minOccurs="0"/>
 *         &lt;element ref="{}dVencimento" minOccurs="0"/>
 *         &lt;element ref="{}ObsInsPagamento" minOccurs="0"/>
 *         &lt;element ref="{}ObrigoMunic" minOccurs="0"/>
 *         &lt;element ref="{}TributacaoISS" minOccurs="0"/>
 *         &lt;element ref="{}CodigoAtividadeEconomica" minOccurs="0"/>
 *         &lt;element ref="{}ServicoViasPublicas" minOccurs="0"/>
 *         &lt;element ref="{}NumeroParcelas" minOccurs="0"/>
 *         &lt;element ref="{}NroOrcamento" minOccurs="0"/>
 *         &lt;element ref="{}CodigoNBS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "valores",
    "localPrestacao",
    "iteListServico",
    "cnae",
    "fPagamento",
    "tributMunicipio",
    "tributMunicDesc",
    "discriminacao",
    "cMun",
    "serQuantidade",
    "serUnidade",
    "serNumAlva",
    "paiPreServico",
    "cMunIncidencia",
    "dVencimento",
    "obsInsPagamento",
    "obrigoMunic",
    "tributacaoISS",
    "codigoAtividadeEconomica",
    "servicoViasPublicas",
    "numeroParcelas",
    "nroOrcamento",
    "codigoNBS"
})
@XmlRootElement(name = "Servico")
public class Servico {

    @XmlElement(name = "Valores", required = true)
    protected Valores valores;
    @XmlElement(name = "LocalPrestacao")
    protected LocalPrestacao localPrestacao;
    @XmlElement(name = "IteListServico", required = true)
    protected String iteListServico;
    @XmlElement(name = "Cnae")
    protected BigInteger cnae;
    protected String fPagamento;
    @XmlElement(name = "TributMunicipio", required = true)
    protected String tributMunicipio;
    @XmlElement(name = "TributMunicDesc")
    protected String tributMunicDesc;
    @XmlElement(name = "Discriminacao", required = true)
    protected String discriminacao;
    @XmlElement(required = true)
    protected BigInteger cMun;
    @XmlElement(name = "SerQuantidade")
    protected BigDecimal serQuantidade;
    @XmlElement(name = "SerUnidade")
    protected String serUnidade;
    @XmlElement(name = "SerNumAlva")
    protected String serNumAlva;
    @XmlElement(name = "PaiPreServico")
    protected String paiPreServico;
    protected BigInteger cMunIncidencia;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dVencimento;
    @XmlElement(name = "ObsInsPagamento")
    protected String obsInsPagamento;
    @XmlElement(name = "ObrigoMunic")
    protected BigInteger obrigoMunic;
    @XmlElement(name = "TributacaoISS")
    protected BigInteger tributacaoISS;
    @XmlElement(name = "CodigoAtividadeEconomica")
    protected String codigoAtividadeEconomica;
    @XmlElement(name = "ServicoViasPublicas")
    protected BigDecimal servicoViasPublicas;
    @XmlElement(name = "NumeroParcelas")
    protected BigDecimal numeroParcelas;
    @XmlElement(name = "NroOrcamento")
    protected BigDecimal nroOrcamento;
    @XmlElement(name = "CodigoNBS")
    protected String codigoNBS;

    /**
     * Gets the value of the valores property.
     * 
     * @return
     *     possible object is
     *     {@link Valores }
     *     
     */
    public Valores getValores() {
        return valores;
    }

    /**
     * Sets the value of the valores property.
     * 
     * @param value
     *     allowed object is
     *     {@link Valores }
     *     
     */
    public void setValores(Valores value) {
        this.valores = value;
    }

    /**
     * Gets the value of the localPrestacao property.
     * 
     * @return
     *     possible object is
     *     {@link LocalPrestacao }
     *     
     */
    public LocalPrestacao getLocalPrestacao() {
        return localPrestacao;
    }

    /**
     * Sets the value of the localPrestacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalPrestacao }
     *     
     */
    public void setLocalPrestacao(LocalPrestacao value) {
        this.localPrestacao = value;
    }

    /**
     * Gets the value of the iteListServico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIteListServico() {
        return iteListServico;
    }

    /**
     * Sets the value of the iteListServico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIteListServico(String value) {
        this.iteListServico = value;
    }

    /**
     * Gets the value of the cnae property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCnae() {
        return cnae;
    }

    /**
     * Sets the value of the cnae property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCnae(BigInteger value) {
        this.cnae = value;
    }

    /**
     * Gets the value of the fPagamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPagamento() {
        return fPagamento;
    }

    /**
     * Sets the value of the fPagamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPagamento(String value) {
        this.fPagamento = value;
    }

    /**
     * Gets the value of the tributMunicipio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTributMunicipio() {
        return tributMunicipio;
    }

    /**
     * Sets the value of the tributMunicipio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTributMunicipio(String value) {
        this.tributMunicipio = value;
    }

    /**
     * Gets the value of the tributMunicDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTributMunicDesc() {
        return tributMunicDesc;
    }

    /**
     * Sets the value of the tributMunicDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTributMunicDesc(String value) {
        this.tributMunicDesc = value;
    }

    /**
     * Gets the value of the discriminacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscriminacao() {
        return discriminacao;
    }

    /**
     * Sets the value of the discriminacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscriminacao(String value) {
        this.discriminacao = value;
    }

    /**
     * Gets the value of the cMun property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCMun() {
        return cMun;
    }

    /**
     * Sets the value of the cMun property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCMun(BigInteger value) {
        this.cMun = value;
    }

    /**
     * Gets the value of the serQuantidade property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSerQuantidade() {
        return serQuantidade;
    }

    /**
     * Sets the value of the serQuantidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSerQuantidade(BigDecimal value) {
        this.serQuantidade = value;
    }

    /**
     * Gets the value of the serUnidade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerUnidade() {
        return serUnidade;
    }

    /**
     * Sets the value of the serUnidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerUnidade(String value) {
        this.serUnidade = value;
    }

    /**
     * Gets the value of the serNumAlva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerNumAlva() {
        return serNumAlva;
    }

    /**
     * Sets the value of the serNumAlva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerNumAlva(String value) {
        this.serNumAlva = value;
    }

    /**
     * Gets the value of the paiPreServico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaiPreServico() {
        return paiPreServico;
    }

    /**
     * Sets the value of the paiPreServico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaiPreServico(String value) {
        this.paiPreServico = value;
    }

    /**
     * Gets the value of the cMunIncidencia property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCMunIncidencia() {
        return cMunIncidencia;
    }

    /**
     * Sets the value of the cMunIncidencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCMunIncidencia(BigInteger value) {
        this.cMunIncidencia = value;
    }

    /**
     * Gets the value of the dVencimento property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDVencimento() {
        return dVencimento;
    }

    /**
     * Sets the value of the dVencimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDVencimento(XMLGregorianCalendar value) {
        this.dVencimento = value;
    }

    /**
     * Gets the value of the obsInsPagamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObsInsPagamento() {
        return obsInsPagamento;
    }

    /**
     * Sets the value of the obsInsPagamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObsInsPagamento(String value) {
        this.obsInsPagamento = value;
    }

    /**
     * Gets the value of the obrigoMunic property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getObrigoMunic() {
        return obrigoMunic;
    }

    /**
     * Sets the value of the obrigoMunic property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setObrigoMunic(BigInteger value) {
        this.obrigoMunic = value;
    }

    /**
     * Gets the value of the tributacaoISS property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTributacaoISS() {
        return tributacaoISS;
    }

    /**
     * Sets the value of the tributacaoISS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTributacaoISS(BigInteger value) {
        this.tributacaoISS = value;
    }

    /**
     * Gets the value of the codigoAtividadeEconomica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoAtividadeEconomica() {
        return codigoAtividadeEconomica;
    }

    /**
     * Sets the value of the codigoAtividadeEconomica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoAtividadeEconomica(String value) {
        this.codigoAtividadeEconomica = value;
    }

    /**
     * Gets the value of the servicoViasPublicas property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getServicoViasPublicas() {
        return servicoViasPublicas;
    }

    /**
     * Sets the value of the servicoViasPublicas property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setServicoViasPublicas(BigDecimal value) {
        this.servicoViasPublicas = value;
    }

    /**
     * Gets the value of the numeroParcelas property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNumeroParcelas() {
        return numeroParcelas;
    }

    /**
     * Sets the value of the numeroParcelas property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNumeroParcelas(BigDecimal value) {
        this.numeroParcelas = value;
    }

    /**
     * Gets the value of the nroOrcamento property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNroOrcamento() {
        return nroOrcamento;
    }

    /**
     * Sets the value of the nroOrcamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNroOrcamento(BigDecimal value) {
        this.nroOrcamento = value;
    }

    /**
     * Gets the value of the codigoNBS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoNBS() {
        return codigoNBS;
    }

    /**
     * Sets the value of the codigoNBS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoNBS(String value) {
        this.codigoNBS = value;
    }

}
