//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.29 at 01:58:16 PM ART 
//


package br.inf.portalfiscal.nfse;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TomaCNPJ" minOccurs="0"/>
 *         &lt;element ref="{}TomaCPF" minOccurs="0"/>
 *         &lt;element ref="{}TomaIM" minOccurs="0"/>
 *         &lt;element ref="{}TomaRazaoSocial" minOccurs="0"/>
 *         &lt;element ref="{}TomatpLgr" minOccurs="0"/>
 *         &lt;element ref="{}TomaEndereco" minOccurs="0"/>
 *         &lt;element ref="{}TomaNumero" minOccurs="0"/>
 *         &lt;element ref="{}TomaComplemento" minOccurs="0"/>
 *         &lt;element ref="{}TomaBairro" minOccurs="0"/>
 *         &lt;element ref="{}TomacMun" minOccurs="0"/>
 *         &lt;element ref="{}TomaxMun" minOccurs="0"/>
 *         &lt;element ref="{}TomaUF" minOccurs="0"/>
 *         &lt;element ref="{}TomaPais" minOccurs="0"/>
 *         &lt;element ref="{}TomaCEP" minOccurs="0"/>
 *         &lt;element ref="{}TomaTelefone" minOccurs="0"/>
 *         &lt;element ref="{}TomaTipoTelefone" minOccurs="0"/>
 *         &lt;element ref="{}TomaEmail" minOccurs="0"/>
 *         &lt;element ref="{}TomaSite" minOccurs="0"/>
 *         &lt;element ref="{}TomaIE" minOccurs="0"/>
 *         &lt;element ref="{}TomaIME" minOccurs="0"/>
 *         &lt;element ref="{}TomaSituacaoEspecial" minOccurs="0"/>
 *         &lt;element ref="{}DocTomadorEstrangeiro" minOccurs="0"/>
 *         &lt;element ref="{}TomaRegEspTrib" minOccurs="0"/>
 *         &lt;element ref="{}TomaCadastroMunicipio" minOccurs="0"/>
 *         &lt;element ref="{}TomaOrgaoPublico" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tomaCNPJ",
    "tomaCPF",
    "tomaIM",
    "tomaRazaoSocial",
    "tomatpLgr",
    "tomaEndereco",
    "tomaNumero",
    "tomaComplemento",
    "tomaBairro",
    "tomacMun",
    "tomaxMun",
    "tomaUF",
    "tomaPais",
    "tomaCEP",
    "tomaTelefone",
    "tomaTipoTelefone",
    "tomaEmail",
    "tomaSite",
    "tomaIE",
    "tomaIME",
    "tomaSituacaoEspecial",
    "docTomadorEstrangeiro",
    "tomaRegEspTrib",
    "tomaCadastroMunicipio",
    "tomaOrgaoPublico"
})
@XmlRootElement(name = "Tomador")
public class Tomador {

    @XmlElement(name = "TomaCNPJ")
    protected String tomaCNPJ;
    @XmlElement(name = "TomaCPF")
    protected String tomaCPF;
    @XmlElement(name = "TomaIM")
    protected String tomaIM;
    @XmlElement(name = "TomaRazaoSocial")
    protected String tomaRazaoSocial;
    @XmlElement(name = "TomatpLgr")
    protected String tomatpLgr;
    @XmlElement(name = "TomaEndereco")
    protected String tomaEndereco;
    @XmlElement(name = "TomaNumero")
    protected String tomaNumero;
    @XmlElement(name = "TomaComplemento")
    protected String tomaComplemento;
    @XmlElement(name = "TomaBairro")
    protected String tomaBairro;
    @XmlElement(name = "TomacMun")
    protected BigInteger tomacMun;
    @XmlElement(name = "TomaxMun")
    protected String tomaxMun;
    @XmlElement(name = "TomaUF")
    protected String tomaUF;
    @XmlElement(name = "TomaPais")
    protected String tomaPais;
    @XmlElement(name = "TomaCEP")
    protected String tomaCEP;
    @XmlElement(name = "TomaTelefone")
    protected String tomaTelefone;
    @XmlElement(name = "TomaTipoTelefone")
    protected String tomaTipoTelefone;
    @XmlElement(name = "TomaEmail")
    protected String tomaEmail;
    @XmlElement(name = "TomaSite")
    protected String tomaSite;
    @XmlElement(name = "TomaIE")
    protected String tomaIE;
    @XmlElement(name = "TomaIME")
    protected String tomaIME;
    @XmlElement(name = "TomaSituacaoEspecial")
    protected String tomaSituacaoEspecial;
    @XmlElement(name = "DocTomadorEstrangeiro")
    protected String docTomadorEstrangeiro;
    @XmlElement(name = "TomaRegEspTrib")
    protected BigDecimal tomaRegEspTrib;
    @XmlElement(name = "TomaCadastroMunicipio")
    protected BigDecimal tomaCadastroMunicipio;
    @XmlElement(name = "TomaOrgaoPublico")
    protected BigDecimal tomaOrgaoPublico;

    /**
     * Gets the value of the tomaCNPJ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomaCNPJ() {
        return tomaCNPJ;
    }

    /**
     * Sets the value of the tomaCNPJ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomaCNPJ(String value) {
        this.tomaCNPJ = value;
    }

    /**
     * Gets the value of the tomaCPF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomaCPF() {
        return tomaCPF;
    }

    /**
     * Sets the value of the tomaCPF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomaCPF(String value) {
        this.tomaCPF = value;
    }

    /**
     * Gets the value of the tomaIM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomaIM() {
        return tomaIM;
    }

    /**
     * Sets the value of the tomaIM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomaIM(String value) {
        this.tomaIM = value;
    }

    /**
     * Gets the value of the tomaRazaoSocial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomaRazaoSocial() {
        return tomaRazaoSocial;
    }

    /**
     * Sets the value of the tomaRazaoSocial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomaRazaoSocial(String value) {
        this.tomaRazaoSocial = value;
    }

    /**
     * Gets the value of the tomatpLgr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomatpLgr() {
        return tomatpLgr;
    }

    /**
     * Sets the value of the tomatpLgr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomatpLgr(String value) {
        this.tomatpLgr = value;
    }

    /**
     * Gets the value of the tomaEndereco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomaEndereco() {
        return tomaEndereco;
    }

    /**
     * Sets the value of the tomaEndereco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomaEndereco(String value) {
        this.tomaEndereco = value;
    }

    /**
     * Gets the value of the tomaNumero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomaNumero() {
        return tomaNumero;
    }

    /**
     * Sets the value of the tomaNumero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomaNumero(String value) {
        this.tomaNumero = value;
    }

    /**
     * Gets the value of the tomaComplemento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomaComplemento() {
        return tomaComplemento;
    }

    /**
     * Sets the value of the tomaComplemento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomaComplemento(String value) {
        this.tomaComplemento = value;
    }

    /**
     * Gets the value of the tomaBairro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomaBairro() {
        return tomaBairro;
    }

    /**
     * Sets the value of the tomaBairro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomaBairro(String value) {
        this.tomaBairro = value;
    }

    /**
     * Gets the value of the tomacMun property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTomacMun() {
        return tomacMun;
    }

    /**
     * Sets the value of the tomacMun property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTomacMun(BigInteger value) {
        this.tomacMun = value;
    }

    /**
     * Gets the value of the tomaxMun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomaxMun() {
        return tomaxMun;
    }

    /**
     * Sets the value of the tomaxMun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomaxMun(String value) {
        this.tomaxMun = value;
    }

    /**
     * Gets the value of the tomaUF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomaUF() {
        return tomaUF;
    }

    /**
     * Sets the value of the tomaUF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomaUF(String value) {
        this.tomaUF = value;
    }

    /**
     * Gets the value of the tomaPais property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomaPais() {
        return tomaPais;
    }

    /**
     * Sets the value of the tomaPais property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomaPais(String value) {
        this.tomaPais = value;
    }

    /**
     * Gets the value of the tomaCEP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomaCEP() {
        return tomaCEP;
    }

    /**
     * Sets the value of the tomaCEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomaCEP(String value) {
        this.tomaCEP = value;
    }

    /**
     * Gets the value of the tomaTelefone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomaTelefone() {
        return tomaTelefone;
    }

    /**
     * Sets the value of the tomaTelefone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomaTelefone(String value) {
        this.tomaTelefone = value;
    }

    /**
     * Gets the value of the tomaTipoTelefone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomaTipoTelefone() {
        return tomaTipoTelefone;
    }

    /**
     * Sets the value of the tomaTipoTelefone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomaTipoTelefone(String value) {
        this.tomaTipoTelefone = value;
    }

    /**
     * Gets the value of the tomaEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomaEmail() {
        return tomaEmail;
    }

    /**
     * Sets the value of the tomaEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomaEmail(String value) {
        this.tomaEmail = value;
    }

    /**
     * Gets the value of the tomaSite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomaSite() {
        return tomaSite;
    }

    /**
     * Sets the value of the tomaSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomaSite(String value) {
        this.tomaSite = value;
    }

    /**
     * Gets the value of the tomaIE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomaIE() {
        return tomaIE;
    }

    /**
     * Sets the value of the tomaIE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomaIE(String value) {
        this.tomaIE = value;
    }

    /**
     * Gets the value of the tomaIME property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomaIME() {
        return tomaIME;
    }

    /**
     * Sets the value of the tomaIME property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomaIME(String value) {
        this.tomaIME = value;
    }

    /**
     * Gets the value of the tomaSituacaoEspecial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomaSituacaoEspecial() {
        return tomaSituacaoEspecial;
    }

    /**
     * Sets the value of the tomaSituacaoEspecial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomaSituacaoEspecial(String value) {
        this.tomaSituacaoEspecial = value;
    }

    /**
     * Gets the value of the docTomadorEstrangeiro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocTomadorEstrangeiro() {
        return docTomadorEstrangeiro;
    }

    /**
     * Sets the value of the docTomadorEstrangeiro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocTomadorEstrangeiro(String value) {
        this.docTomadorEstrangeiro = value;
    }

    /**
     * Gets the value of the tomaRegEspTrib property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTomaRegEspTrib() {
        return tomaRegEspTrib;
    }

    /**
     * Sets the value of the tomaRegEspTrib property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTomaRegEspTrib(BigDecimal value) {
        this.tomaRegEspTrib = value;
    }

    /**
     * Gets the value of the tomaCadastroMunicipio property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTomaCadastroMunicipio() {
        return tomaCadastroMunicipio;
    }

    /**
     * Sets the value of the tomaCadastroMunicipio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTomaCadastroMunicipio(BigDecimal value) {
        this.tomaCadastroMunicipio = value;
    }

    /**
     * Gets the value of the tomaOrgaoPublico property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTomaOrgaoPublico() {
        return tomaOrgaoPublico;
    }

    /**
     * Sets the value of the tomaOrgaoPublico property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTomaOrgaoPublico(BigDecimal value) {
        this.tomaOrgaoPublico = value;
    }

}
