//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.29 at 01:58:16 PM ART 
//


package br.inf.portalfiscal.nfse;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TraNome"/>
 *         &lt;element ref="{}TraCPFCNPJ" minOccurs="0"/>
 *         &lt;element ref="{}TraIE" minOccurs="0"/>
 *         &lt;element ref="{}TraPlaca" minOccurs="0"/>
 *         &lt;element ref="{}TraEnd" minOccurs="0"/>
 *         &lt;element ref="{}TraMun" minOccurs="0"/>
 *         &lt;element ref="{}TraUF" minOccurs="0"/>
 *         &lt;element ref="{}TraPais" minOccurs="0"/>
 *         &lt;element ref="{}TraTipoFrete" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "traNome",
    "traCPFCNPJ",
    "traIE",
    "traPlaca",
    "traEnd",
    "traMun",
    "traUF",
    "traPais",
    "traTipoFrete"
})
@XmlRootElement(name = "Transportadora")
public class Transportadora {

    @XmlElement(name = "TraNome", required = true)
    protected String traNome;
    @XmlElement(name = "TraCPFCNPJ")
    protected String traCPFCNPJ;
    @XmlElement(name = "TraIE")
    protected String traIE;
    @XmlElement(name = "TraPlaca")
    protected String traPlaca;
    @XmlElement(name = "TraEnd")
    protected String traEnd;
    @XmlElement(name = "TraMun")
    protected BigInteger traMun;
    @XmlElement(name = "TraUF")
    protected String traUF;
    @XmlElement(name = "TraPais")
    protected String traPais;
    @XmlElement(name = "TraTipoFrete")
    protected BigInteger traTipoFrete;

    /**
     * Gets the value of the traNome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTraNome() {
        return traNome;
    }

    /**
     * Sets the value of the traNome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTraNome(String value) {
        this.traNome = value;
    }

    /**
     * Gets the value of the traCPFCNPJ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTraCPFCNPJ() {
        return traCPFCNPJ;
    }

    /**
     * Sets the value of the traCPFCNPJ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTraCPFCNPJ(String value) {
        this.traCPFCNPJ = value;
    }

    /**
     * Gets the value of the traIE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTraIE() {
        return traIE;
    }

    /**
     * Sets the value of the traIE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTraIE(String value) {
        this.traIE = value;
    }

    /**
     * Gets the value of the traPlaca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTraPlaca() {
        return traPlaca;
    }

    /**
     * Sets the value of the traPlaca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTraPlaca(String value) {
        this.traPlaca = value;
    }

    /**
     * Gets the value of the traEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTraEnd() {
        return traEnd;
    }

    /**
     * Sets the value of the traEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTraEnd(String value) {
        this.traEnd = value;
    }

    /**
     * Gets the value of the traMun property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTraMun() {
        return traMun;
    }

    /**
     * Sets the value of the traMun property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTraMun(BigInteger value) {
        this.traMun = value;
    }

    /**
     * Gets the value of the traUF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTraUF() {
        return traUF;
    }

    /**
     * Sets the value of the traUF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTraUF(String value) {
        this.traUF = value;
    }

    /**
     * Gets the value of the traPais property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTraPais() {
        return traPais;
    }

    /**
     * Sets the value of the traPais property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTraPais(String value) {
        this.traPais = value;
    }

    /**
     * Gets the value of the traTipoFrete property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTraTipoFrete() {
        return traTipoFrete;
    }

    /**
     * Sets the value of the traTipoFrete property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTraTipoFrete(BigInteger value) {
        this.traTipoFrete = value;
    }

}
