//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.29 at 01:58:16 PM ART 
//


package br.inf.portalfiscal.nfse;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ValServicos" minOccurs="0"/>
 *         &lt;element ref="{}ValDeducoes" minOccurs="0"/>
 *         &lt;element ref="{}ValPIS" minOccurs="0"/>
 *         &lt;element ref="{}ValBCPIS" minOccurs="0"/>
 *         &lt;element ref="{}ValCOFINS" minOccurs="0"/>
 *         &lt;element ref="{}ValBCCOFINS" minOccurs="0"/>
 *         &lt;element ref="{}ValINSS" minOccurs="0"/>
 *         &lt;element ref="{}ValBCINSS" minOccurs="0"/>
 *         &lt;element ref="{}ValIR" minOccurs="0"/>
 *         &lt;element ref="{}ValBCIRRF" minOccurs="0"/>
 *         &lt;element ref="{}ValCSLL" minOccurs="0"/>
 *         &lt;element ref="{}ValBCCSLL" minOccurs="0"/>
 *         &lt;element ref="{}ISSRetido" minOccurs="0"/>
 *         &lt;element ref="{}RespRetencao" minOccurs="0"/>
 *         &lt;element ref="{}Tributavel" minOccurs="0"/>
 *         &lt;element ref="{}ValISS" minOccurs="0"/>
 *         &lt;element ref="{}ValISSRetido" minOccurs="0"/>
 *         &lt;element ref="{}ValOutrasRetencoes" minOccurs="0"/>
 *         &lt;element ref="{}ValTotal" minOccurs="0"/>
 *         &lt;element ref="{}ValBaseCalculo" minOccurs="0"/>
 *         &lt;element ref="{}ValAliqISS" minOccurs="0"/>
 *         &lt;element ref="{}ValAliqPIS" minOccurs="0"/>
 *         &lt;element ref="{}ValAliqCOFINS" minOccurs="0"/>
 *         &lt;element ref="{}ValAliqIR" minOccurs="0"/>
 *         &lt;element ref="{}ValAliqCSLL" minOccurs="0"/>
 *         &lt;element ref="{}ValAliqINSS" minOccurs="0"/>
 *         &lt;element ref="{}ValLiquido" minOccurs="0"/>
 *         &lt;element ref="{}ValDescIncond" minOccurs="0"/>
 *         &lt;element ref="{}ValDescCond" minOccurs="0"/>
 *         &lt;element ref="{}ValAliqISSoMunic" minOccurs="0"/>
 *         &lt;element ref="{}InfValPIS" minOccurs="0"/>
 *         &lt;element ref="{}InfValCOFINS" minOccurs="0"/>
 *         &lt;element ref="{}ValLiqFatura" minOccurs="0"/>
 *         &lt;element ref="{}ValBCISSRetido" minOccurs="0"/>
 *         &lt;element ref="{}NroFatura" minOccurs="0"/>
 *         &lt;element ref="{}CargaTribValor" minOccurs="0"/>
 *         &lt;element ref="{}CargaTribPercentual" minOccurs="0"/>
 *         &lt;element ref="{}CargaTribFonte" minOccurs="0"/>
 *         &lt;element ref="{}JustDed" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "valServicos",
    "valDeducoes",
    "valPIS",
    "valBCPIS",
    "valCOFINS",
    "valBCCOFINS",
    "valINSS",
    "valBCINSS",
    "valIR",
    "valBCIRRF",
    "valCSLL",
    "valBCCSLL",
    "issRetido",
    "respRetencao",
    "tributavel",
    "valISS",
    "valISSRetido",
    "valOutrasRetencoes",
    "valTotal",
    "valBaseCalculo",
    "valAliqISS",
    "valAliqPIS",
    "valAliqCOFINS",
    "valAliqIR",
    "valAliqCSLL",
    "valAliqINSS",
    "valLiquido",
    "valDescIncond",
    "valDescCond",
    "valAliqISSoMunic",
    "infValPIS",
    "infValCOFINS",
    "valLiqFatura",
    "valBCISSRetido",
    "nroFatura",
    "cargaTribValor",
    "cargaTribPercentual",
    "cargaTribFonte",
    "justDed"
})
@XmlRootElement(name = "Valores")
public class Valores {

    @XmlElement(name = "ValServicos")
    protected BigDecimal valServicos;
    @XmlElement(name = "ValDeducoes")
    protected BigDecimal valDeducoes;
    @XmlElement(name = "ValPIS")
    protected BigDecimal valPIS;
    @XmlElement(name = "ValBCPIS")
    protected BigDecimal valBCPIS;
    @XmlElement(name = "ValCOFINS")
    protected BigDecimal valCOFINS;
    @XmlElement(name = "ValBCCOFINS")
    protected BigDecimal valBCCOFINS;
    @XmlElement(name = "ValINSS")
    protected BigDecimal valINSS;
    @XmlElement(name = "ValBCINSS")
    protected BigDecimal valBCINSS;
    @XmlElement(name = "ValIR")
    protected BigDecimal valIR;
    @XmlElement(name = "ValBCIRRF")
    protected BigDecimal valBCIRRF;
    @XmlElement(name = "ValCSLL")
    protected BigDecimal valCSLL;
    @XmlElement(name = "ValBCCSLL")
    protected BigDecimal valBCCSLL;
    @XmlElement(name = "ISSRetido")
    protected Integer issRetido;
    @XmlElement(name = "RespRetencao")
    protected Integer respRetencao;
    @XmlElement(name = "Tributavel")
    protected String tributavel;
    @XmlElement(name = "ValISS")
    protected BigDecimal valISS;
    @XmlElement(name = "ValISSRetido")
    protected BigDecimal valISSRetido;
    @XmlElement(name = "ValOutrasRetencoes")
    protected BigDecimal valOutrasRetencoes;
    @XmlElement(name = "ValTotal")
    protected BigDecimal valTotal;
    @XmlElement(name = "ValBaseCalculo")
    protected BigDecimal valBaseCalculo;
    @XmlElement(name = "ValAliqISS")
    protected BigDecimal valAliqISS;
    @XmlElement(name = "ValAliqPIS")
    protected BigDecimal valAliqPIS;
    @XmlElement(name = "ValAliqCOFINS")
    protected BigDecimal valAliqCOFINS;
    @XmlElement(name = "ValAliqIR")
    protected BigDecimal valAliqIR;
    @XmlElement(name = "ValAliqCSLL")
    protected BigDecimal valAliqCSLL;
    @XmlElement(name = "ValAliqINSS")
    protected BigDecimal valAliqINSS;
    @XmlElement(name = "ValLiquido")
    protected BigDecimal valLiquido;
    @XmlElement(name = "ValDescIncond")
    protected BigDecimal valDescIncond;
    @XmlElement(name = "ValDescCond")
    protected BigDecimal valDescCond;
    @XmlElement(name = "ValAliqISSoMunic")
    protected BigDecimal valAliqISSoMunic;
    @XmlElement(name = "InfValPIS")
    protected BigDecimal infValPIS;
    @XmlElement(name = "InfValCOFINS")
    protected BigDecimal infValCOFINS;
    @XmlElement(name = "ValLiqFatura")
    protected BigDecimal valLiqFatura;
    @XmlElement(name = "ValBCISSRetido")
    protected BigDecimal valBCISSRetido;
    @XmlElement(name = "NroFatura")
    protected BigDecimal nroFatura;
    @XmlElement(name = "CargaTribValor")
    protected BigDecimal cargaTribValor;
    @XmlElement(name = "CargaTribPercentual")
    protected BigDecimal cargaTribPercentual;
    @XmlElement(name = "CargaTribFonte")
    protected String cargaTribFonte;
    @XmlElement(name = "JustDed")
    protected String justDed;

    /**
     * Gets the value of the valServicos property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValServicos() {
        return valServicos;
    }

    /**
     * Sets the value of the valServicos property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValServicos(BigDecimal value) {
        this.valServicos = value;
    }

    /**
     * Gets the value of the valDeducoes property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValDeducoes() {
        return valDeducoes;
    }

    /**
     * Sets the value of the valDeducoes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValDeducoes(BigDecimal value) {
        this.valDeducoes = value;
    }

    /**
     * Gets the value of the valPIS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValPIS() {
        return valPIS;
    }

    /**
     * Sets the value of the valPIS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValPIS(BigDecimal value) {
        this.valPIS = value;
    }

    /**
     * Gets the value of the valBCPIS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValBCPIS() {
        return valBCPIS;
    }

    /**
     * Sets the value of the valBCPIS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValBCPIS(BigDecimal value) {
        this.valBCPIS = value;
    }

    /**
     * Gets the value of the valCOFINS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValCOFINS() {
        return valCOFINS;
    }

    /**
     * Sets the value of the valCOFINS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValCOFINS(BigDecimal value) {
        this.valCOFINS = value;
    }

    /**
     * Gets the value of the valBCCOFINS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValBCCOFINS() {
        return valBCCOFINS;
    }

    /**
     * Sets the value of the valBCCOFINS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValBCCOFINS(BigDecimal value) {
        this.valBCCOFINS = value;
    }

    /**
     * Gets the value of the valINSS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValINSS() {
        return valINSS;
    }

    /**
     * Sets the value of the valINSS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValINSS(BigDecimal value) {
        this.valINSS = value;
    }

    /**
     * Gets the value of the valBCINSS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValBCINSS() {
        return valBCINSS;
    }

    /**
     * Sets the value of the valBCINSS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValBCINSS(BigDecimal value) {
        this.valBCINSS = value;
    }

    /**
     * Gets the value of the valIR property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValIR() {
        return valIR;
    }

    /**
     * Sets the value of the valIR property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValIR(BigDecimal value) {
        this.valIR = value;
    }

    /**
     * Gets the value of the valBCIRRF property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValBCIRRF() {
        return valBCIRRF;
    }

    /**
     * Sets the value of the valBCIRRF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValBCIRRF(BigDecimal value) {
        this.valBCIRRF = value;
    }

    /**
     * Gets the value of the valCSLL property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValCSLL() {
        return valCSLL;
    }

    /**
     * Sets the value of the valCSLL property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValCSLL(BigDecimal value) {
        this.valCSLL = value;
    }

    /**
     * Gets the value of the valBCCSLL property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValBCCSLL() {
        return valBCCSLL;
    }

    /**
     * Sets the value of the valBCCSLL property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValBCCSLL(BigDecimal value) {
        this.valBCCSLL = value;
    }

    /**
     * Gets the value of the issRetido property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getISSRetido() {
        return issRetido;
    }

    /**
     * Sets the value of the issRetido property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setISSRetido(Integer value) {
        this.issRetido = value;
    }

    /**
     * Gets the value of the respRetencao property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRespRetencao() {
        return respRetencao;
    }

    /**
     * Sets the value of the respRetencao property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRespRetencao(Integer value) {
        this.respRetencao = value;
    }

    /**
     * Gets the value of the tributavel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTributavel() {
        return tributavel;
    }

    /**
     * Sets the value of the tributavel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTributavel(String value) {
        this.tributavel = value;
    }

    /**
     * Gets the value of the valISS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValISS() {
        return valISS;
    }

    /**
     * Sets the value of the valISS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValISS(BigDecimal value) {
        this.valISS = value;
    }

    /**
     * Gets the value of the valISSRetido property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValISSRetido() {
        return valISSRetido;
    }

    /**
     * Sets the value of the valISSRetido property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValISSRetido(BigDecimal value) {
        this.valISSRetido = value;
    }

    /**
     * Gets the value of the valOutrasRetencoes property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValOutrasRetencoes() {
        return valOutrasRetencoes;
    }

    /**
     * Sets the value of the valOutrasRetencoes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValOutrasRetencoes(BigDecimal value) {
        this.valOutrasRetencoes = value;
    }

    /**
     * Gets the value of the valTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValTotal() {
        return valTotal;
    }

    /**
     * Sets the value of the valTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValTotal(BigDecimal value) {
        this.valTotal = value;
    }

    /**
     * Gets the value of the valBaseCalculo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValBaseCalculo() {
        return valBaseCalculo;
    }

    /**
     * Sets the value of the valBaseCalculo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValBaseCalculo(BigDecimal value) {
        this.valBaseCalculo = value;
    }

    /**
     * Gets the value of the valAliqISS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValAliqISS() {
        return valAliqISS;
    }

    /**
     * Sets the value of the valAliqISS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValAliqISS(BigDecimal value) {
        this.valAliqISS = value;
    }

    /**
     * Gets the value of the valAliqPIS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValAliqPIS() {
        return valAliqPIS;
    }

    /**
     * Sets the value of the valAliqPIS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValAliqPIS(BigDecimal value) {
        this.valAliqPIS = value;
    }

    /**
     * Gets the value of the valAliqCOFINS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValAliqCOFINS() {
        return valAliqCOFINS;
    }

    /**
     * Sets the value of the valAliqCOFINS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValAliqCOFINS(BigDecimal value) {
        this.valAliqCOFINS = value;
    }

    /**
     * Gets the value of the valAliqIR property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValAliqIR() {
        return valAliqIR;
    }

    /**
     * Sets the value of the valAliqIR property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValAliqIR(BigDecimal value) {
        this.valAliqIR = value;
    }

    /**
     * Gets the value of the valAliqCSLL property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValAliqCSLL() {
        return valAliqCSLL;
    }

    /**
     * Sets the value of the valAliqCSLL property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValAliqCSLL(BigDecimal value) {
        this.valAliqCSLL = value;
    }

    /**
     * Gets the value of the valAliqINSS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValAliqINSS() {
        return valAliqINSS;
    }

    /**
     * Sets the value of the valAliqINSS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValAliqINSS(BigDecimal value) {
        this.valAliqINSS = value;
    }

    /**
     * Gets the value of the valLiquido property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValLiquido() {
        return valLiquido;
    }

    /**
     * Sets the value of the valLiquido property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValLiquido(BigDecimal value) {
        this.valLiquido = value;
    }

    /**
     * Gets the value of the valDescIncond property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValDescIncond() {
        return valDescIncond;
    }

    /**
     * Sets the value of the valDescIncond property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValDescIncond(BigDecimal value) {
        this.valDescIncond = value;
    }

    /**
     * Gets the value of the valDescCond property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValDescCond() {
        return valDescCond;
    }

    /**
     * Sets the value of the valDescCond property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValDescCond(BigDecimal value) {
        this.valDescCond = value;
    }

    /**
     * Gets the value of the valAliqISSoMunic property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValAliqISSoMunic() {
        return valAliqISSoMunic;
    }

    /**
     * Sets the value of the valAliqISSoMunic property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValAliqISSoMunic(BigDecimal value) {
        this.valAliqISSoMunic = value;
    }

    /**
     * Gets the value of the infValPIS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInfValPIS() {
        return infValPIS;
    }

    /**
     * Sets the value of the infValPIS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInfValPIS(BigDecimal value) {
        this.infValPIS = value;
    }

    /**
     * Gets the value of the infValCOFINS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInfValCOFINS() {
        return infValCOFINS;
    }

    /**
     * Sets the value of the infValCOFINS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInfValCOFINS(BigDecimal value) {
        this.infValCOFINS = value;
    }

    /**
     * Gets the value of the valLiqFatura property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValLiqFatura() {
        return valLiqFatura;
    }

    /**
     * Sets the value of the valLiqFatura property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValLiqFatura(BigDecimal value) {
        this.valLiqFatura = value;
    }

    /**
     * Gets the value of the valBCISSRetido property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValBCISSRetido() {
        return valBCISSRetido;
    }

    /**
     * Sets the value of the valBCISSRetido property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValBCISSRetido(BigDecimal value) {
        this.valBCISSRetido = value;
    }

    /**
     * Gets the value of the nroFatura property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNroFatura() {
        return nroFatura;
    }

    /**
     * Sets the value of the nroFatura property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNroFatura(BigDecimal value) {
        this.nroFatura = value;
    }

    /**
     * Gets the value of the cargaTribValor property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCargaTribValor() {
        return cargaTribValor;
    }

    /**
     * Sets the value of the cargaTribValor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCargaTribValor(BigDecimal value) {
        this.cargaTribValor = value;
    }

    /**
     * Gets the value of the cargaTribPercentual property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCargaTribPercentual() {
        return cargaTribPercentual;
    }

    /**
     * Sets the value of the cargaTribPercentual property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCargaTribPercentual(BigDecimal value) {
        this.cargaTribPercentual = value;
    }

    /**
     * Gets the value of the cargaTribFonte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCargaTribFonte() {
        return cargaTribFonte;
    }

    /**
     * Sets the value of the cargaTribFonte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCargaTribFonte(String value) {
        this.cargaTribFonte = value;
    }

    /**
     * Gets the value of the justDed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJustDed() {
        return justDed;
    }

    /**
     * Sets the value of the justDed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJustDed(String value) {
        this.justDed = value;
    }

}
