package com.midas.api.constant;

public enum FsNfseNatOp {
	TRIB_MUNIC("1"), TRIB_FORA_MUNIC("2"), ISENCAO("3"), IMUNE("4"), EXIG_SUSP_DECIS_JUDIC("5"), EXIG_SUSP_PROC_ADMN("6"), 
	EXIGIVEL("7"), NAO_INCIDENCIA("8"), EXPORTACAO("9"), ISS_FIXO("10"), SUBST_TRIB("11"), SN("12"), ISENCAO_PARCIAL("13"), 
	CANCELADO("14"), IIS_RETID_TOMA_INTERM("15"), NAO_TRIB("16"), MEI("17"), SERV_IMOVEL("18"), SERV_VIA_PUBLICA("19"), 
	TRIB_INTEG_ISSRF_REC_TOMA_OPM("20"), TRIB_REDUC_BC("21"), TRIB_REDUC_BC_ISSRF_REC_TOMA_OPM("22"), 
	TRIB_REDUC_BC_SUJ_SUBS_TRIB_REC_TOMA_NAO_OPM("23"), NAO_TRIB_ISS_REG_ESTIMATIVA("24"), NAO_TRIB_ISS_CONST_CIV_REC_ANT("25"), 
	NAO_TRIB_ATO_COOP("26"), SN_ISS_RET_FONTE("27"), SUBS_TRIB_AGENC_INTERM_PREST_SERV("28"), SN_SUBS_TRIB("29"), ISS_RET_ANT_SUBS_TRIB("30"), 
	TRIB_REDUC_BC_ALQ_ISS_RET_FONTE("31"), TRIB_REDUC_BC_ALIQ_SUJ_REG_SUBS_TRIB("32"), TRIB_REDUC_BC_ALIQ_ISS_RET_ANT_SUBS_TRIB("33"), 
	NAO_TRIB_RAZ_DEST_BENS_OBJ_MERC_PARA_IND_COMERC("34"), NAO_TRIB_RAZ_DIFER_PREST_SERV("35"), TRIB_MUNIC_ISENTO("36"), 
	TRIB_FORA_MUNIC_ISENTO("37"), TRIB_MUNIC_IMUNE("38"), TRIB_FORA_MUNIC_IMUNE("39"), TRIB_MUNIC_EXIGIB_SUSP("40"), 
	TRIB_FORA_MUNIC_EXIGIB_SUSP("41"), ESTIMADO("43"), IMPOS_DEV_MUNIC_OBRIG_RET_FONTE_SPM("51"), IMPOS_DEV_MUNIC_SEM_OBRIG_RET_FONTE_SPM("52"), 
	NAO_TRIB_SPM("58"), IMPOS_RECOL_REG_UN_ARREC_SN_SPM("59"), IMPOS_DEV_MUNIC_OBRIG_RET_FONTE_SPFM("61"), 
	IMPOS_DEV_MUNIC_SEM_OBRIG_RET_FONTE_SPFM("62"), IMPOS_DEV_FORA_MUNIC_OBRIG_RET_FONTE_SPFM("63"), 
	IMPOS_DEV_FORA_MUNIC_SEM_OBRIG_RET_FONTE_SPFM("64"), NAO_TRIB_SPFM("68"), IMPOS_RECOL_REG_UN_ARREC_SN_SPFM("69"), NAO_TRIB_SPE("78"), 
	ISS_DEV_MUNIC_SN("501"), ISS_DEV_OUT_MUNIC_SN("502"), SPM_ISS_MENS_SEM_RET_FONTE("511"), SPM_ISS_MENS_RET_FONTE("512"), 
	CCM_ISS_MENS_SEM_RET_FONTE("521"), CCM_ISS_MENS_RET_FONTE("522"), ESCRIT_CONTAB_SN("551"), ISS_RET_TOMA_INTERM_SN("601"), 
	SPFM_ISS_MENS_SEM_RET_FONTE("611"), SPFM_ISS_MENS_RET_FONTE("612"), CCOM_ISS_MENS_SEM_RET_FONTE("621"), CCOM_ISS_MENS_RET_FONTE("622"), 
	OP_IMUNE_ISENTA_NAO_TRIB_SN("701"), SP_NAO_ENQ_SIT_ANT_SEM_RET("911"), SP_NAO_ENQ_SIT_ANT_RET("912");

	private String descricao;

	private FsNfseNatOp(String descricao) {
		this.descricao = descricao;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
}
