//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 10:39:09 AM BRT 
//


package br.inf.portalfiscal.mdfe;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.inf.portalfiscal.mdfe package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory_rodo {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.inf.portalfiscal.mdfe
     * 
     */
    public ObjectFactory_rodo() {
    }

    /**
     * Create an instance of {@link Rodo }
     * 
     */
    public Rodo createRodo() {
        return new Rodo();
    }

    /**
     * Create an instance of {@link Rodo.ValePed }
     * 
     */
   /* public Rodo.ValePed createRodoValePed() {
        return new Rodo.ValePed();
    }*/

    /**
     * Create an instance of {@link Rodo.VeicReboque }
     * 
     */
    public Rodo.VeicReboque createRodoVeicReboque() {
        return new Rodo.VeicReboque();
    }

    /**
     * Create an instance of {@link Rodo.VeicTracao }
     * 
     */
    public Rodo.VeicTracao createRodoVeicTracao() {
        return new Rodo.VeicTracao();
    }

    /**
     * Create an instance of {@link Rodo.ValePed.Disp }
     * 
     */
   /* public Rodo.ValePed.Disp createRodoValePedDisp() {
        return new Rodo.ValePed.Disp();
    }*/

    /**
     * Create an instance of {@link Rodo.VeicReboque.Prop }
     * 
     */
    public Rodo.VeicReboque.Prop createRodoVeicReboqueProp() {
        return new Rodo.VeicReboque.Prop();
    }

    /**
     * Create an instance of {@link Rodo.VeicTracao.Prop }
     * 
     */
    public Rodo.VeicTracao.Prop createRodoVeicTracaoProp() {
        return new Rodo.VeicTracao.Prop();
    }

    /**
     * Create an instance of {@link Rodo.VeicTracao.Condutor }
     * 
     */
    public Rodo.VeicTracao.Condutor createRodoVeicTracaoCondutor() {
        return new Rodo.VeicTracao.Condutor();
    }

}
