spring:
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        type: trace
  servlet: 
    multipart: 
      max-file-size: 5MB
      max-request-size: 5MB      
      
server:    
  servlet:
    context-path: /api
  port: 8080
  
multitenancy:
  mtapp:
    master:
      datasource:
        url: jdbc:mysql://localhost:3306/midas
        username: root
        password: unisul.123
        driverClassName: com.mysql.cj.jdbc.Driver
        connectionTimeout: 20000
        maxPoolSize: 250
        idleTimeout: 300000
        minIdle: 5
        poolName: masterdb-connection-pool